repos:
- repo: local
  hooks:
  - id: poetry-install
    name: Poetry Install
    stages:
    - post-checkout
    - post-commit
    language: system
    entry: poetry install -q --sync
    pass_filenames: false
    files: ^poetry.lock$

  - id: poetry-check
    name: Check Poetry Config
    description: run poetry check to validate config
    stages: [commit]
    entry: poetry check
    language: python
    language_version: python3
    pass_filenames: false
    files: ^pyproject.toml|poetry.lock|poetry.toml$

  - id: poetry-lock
    name: Make sure poetry dependencies are locked correctly
    description: run poetry lock to update lock file
    stages: [commit]
    entry: poetry lock --no-update
    language: python
    language_version: python3
    files: ^pyproject.toml|poetry.lock$
    pass_filenames: false

  - id: poetry-export
    name: Export Poetry Packages
    description: run poetry export to sync lock file with requirements.txt
    stages: [commit]
    entry: poetry export
    language: python
    language_version: python3
    pass_filenames: false
    files: ^poetry.lock|requirements.txt$
    args: [-f, requirements.txt, -o, requirements.txt]

  - id: poetry-export-serving
    name: Export Poetry Packages for Serving
    description: run poetry export to sync lock file with serving_requirements.txt
    stages: [commit]
    entry: poetry export
    language: python
    language_version: python3
    pass_filenames: false
    files: ^poetry.lock|serving_requirements.txt$
    args: [-f, requirements.txt, -o, serving_requirements.txt, --only, serving]

default_install_hook_types:
- pre-commit
- commit-msg
- post-checkout
- post-commit
