tokens: tuple[str, ...] = ('[[nil]]',
  '[[mask]]',
  '##ed', # past tense verb suffix like in attacked
  '##er', # verb suffix to make a noun for actor like in attacker
  '##ing', # active tense verb suffix like in attacking
  '##s', # plural noun s suffix like in players
  '##vs', # verb s suffix like in attacks
  '##est', 
  'winch',
  'pig',
  'ir',
  'dungeon master',
  'horde',
  '"uncovered cavern"',
  'nay-igpay-atinlay',
  "\"i'm coming, too!\"",
  'component',
  'aaah!',
  'elite',
  'form',
  '−',
  'sneak',
  'happen',
  '?',
  "'",
  ')',
  'yes',
  "'s",
  "bolas's meditation realm",
  "city's blessing",
  "serra's realm",
  'deep, booming voice, "presenting . . . "',
  'scariest',
  "shuffle all cards in the game together and deal them into three deck. the game continues with a new player.",
  "sneak into your parents' closet to get a deck. your new brother is joining",
  "urza's",
  '"ach! hans, run! it\'s the . . ."',
  '"thank you, sir. may i have another?"',
  '"uncovered cavern"',
  '!',
  'n, r, s, or t',
  '"',
  '&',
  '*',
  'frenzy',
  '+',
  ',',
  '-',
  '.',
  '.5',
  '/',
  '0',
  '1',
  '1,000',
  '10',
  '100',
  'windgrace',
  '1000000',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '2',
  '20',
  '200',
  '25',
  '26',
  '3',
  '30',
  '4',
  '40',
  '5',
  '50',
  '6',
  '7',
  '8',
  '9',
  '99',
  ':',
  ';',
  '[',
  '[[bureaucracy]]',
  '[[bureaucracycond]]',
  '[[card]]',
  '[[cost]]',
  '[[loyalty]]',
  '[[oracle]]',
  '[[power]]',
  '[[toughness]]',
  '[[type]]',
  '\n',
  ']',
  '__________',
  'a',
  'abian',
  'ability',
  'able',
  'above',
  'absolutely-removed-from-the-freaking-game-forever',
  'absorb',
  'accept',
  'acorn',
  'action',
  'activate',
  'active',
  'activation',
  'adapt',
  'add',
  'addition',
  'additional',
  'adventure',
  'adventuring',
  'advise',
  'advisor',
  'advocate',
  'aegis',
  'aetherborn',
  'affect',
  'affinity',
  'afflict',
  'after',
  'afterlife',
  'aftermath',
  'again',
  'against',
  'age',
  'agenda',
  'agents of s.n.e.a.k.', #UN
  'aggressive',
  'aim',
  'air',
  'ajani',
  'alara',
  'alien',
  'alive',
  'all',
  'allows richard to propose marriage to lily. if the proposal is accepted both players win; mix the cards in play, both libraries, and both graveyards as a shared deck.',
  'ally',
  'alone',
  'alphabet', #UN
  'alphabetically', #UN
  'already',
  'also',
  'amass',
  'american', #UN
  'aminatou',
  'among',
  'amount',
  'amplify',
  'and',
  'and/or',
  'angel',
  'angrath',
  'annihilator',
  'answer', # UN
  'ante',
  'antelope',
  'antiquities',
  'any',
  'anytime',
  'anywhere',
  'ape',
  'appears', # UN
  'apply',
  'arabian nights',
  'arachnus web',
  'arcane',
  'archer',
  'archon',
  'are',
  'area',
  'arkhos',
  'arlinn',
  'arm', # UN
  'army',
  'arrow',
  'arrowhead',
  'art',
  'artifact',
  'artificer',
  'artist',
  'as',
  'ascend',
  'ashiok',
  'ask', # UN
  'assassin',
  'assemble', # UN
  'assembly-worker',
  'assign',
  'assist',
  'at',
  'atog',
  'attach',
  'attack',
  'audibly flicks', # UN
  'augment', # UN
  'aura',
  'aurochs',
  'autobot', # UN
  'autumn',
  'avatar',
  'awaken',
  'awakening',
  'aware',
  'away',
  'azgol',
  'azra',
  'back',
  'badger',
  'bahamut',
  'balance',
  'ban',
  'band',
  'bank',
  'barbarian',
  'bard',
  'base',
  'basic',
  'basilisk',
  'basri',
  'bat',
  'battle cry',
  'battlefield',
  'bear',
  'beast',
  'beaver',
  'become',
  'beeble',
  'been',
  'before',
  'begin',
  'behemoth',
  'behind',
  'beholder',
  'being',
  'belenon',
  'bell',
  'below',
  'bend',
  'beneath',
  'berserker',
  'best',
  'bestow',
  'between',
  'beyond',
  'bid',
  'bird',
  'black',
  'bland',
  'blank',
  'blaze',
  'blinkmoth',
  'block',
  'blood',
  'bloodline',
  'bloodthirst',
  'blue',
  'blurry',
  'boar',
  'boast',
  'body',
  'bolas',
  'bolster',
  'book',
  'booster',
  'border',
  'both',
  'bottom',
  'bound',
  'bounty',
  'bow',
  'box',
  'bracketed',
  'brainiac',
  'breath-holding',
  'bribery',
  'brick',
  'bringer',
  'brushwagg',
  'bureaucrat',
  'bushido',
  'buyback',
  'buzz',
  'by',
  'cage',
  'calix',
  'camarid',
  'came',
  'camel',
  'can',
  'capital',
  'card',
  'caribou',
  'carrier',
  'carrion',
  'cartouche',
  'cascade',
  'cast',
  'cat',
  'catch',
  'cause',
  'ceases',
  'centaur',
  'cephalid',
  'chair',
  'challenge',
  'chameleon',
  'champion',
  'chandra',
  'change',
  'changeling',
  'chaos',
  'characteristics',
  'charge',
  'charisma check',
  'chicken',
  'child',
  'chimera',
  'chip',
  'choice',
  'choose',
  'chorus',
  'chosen',
  'chronicle',
  'cipher',
  'citizen',
  'clamfolk',
  'clap',
  'clash',
  'class',
  'cleanup',
  'cleave',
  'cleric',
  'closest',
  'clothing',
  'cluck',
  'clue',
  'cockatrice',
  'coin',
  'collector number',
  'color',
  'combat',
  'combination',
  'combine',
  'come',
  'command',
  'commander',
  'common',
  'compleated',
  'complete',
  'completely',
  'compliment',
  'condemnation',
  'consonant',
  'conspiracy',
  'conspire',
  'construct',
  'constructed format',
  'consumes and confuses',
  'contains',
  'continues',
  'continuously',
  'contraption',
  'control',
  'convert',
  'convoke',
  'copy',
  'corpse',
  'correct',
  'correctly',
  'corruption',
  'cost',
  'could',
  'count',
  'counter',
  'counts',
  'cover',
  'cow',
  'coward',
  'crab',
  'crank',
  'create',
  'creature',
  'credit',
  'crew',
  'croak',
  'crocodile',
  'crossbreed labs',
  'crow',
  'crystal',
  'cube',
  'cumulative',
  'currency',
  'current hour',
  'curse',
  'cyborg',
  'cycle',
  'cyclops',
  'dack',
  'dakkon',
  'damage',
  'daretti',
  'dark outdoors',
  'dash',
  'dauthi',
  'davriel',
  'day',
  'deal',
  'death',
  'deathtouch',
  'decayed',
  'decide',
  'deck',
  'declare',
  'deer',
  'defender',
  'defending',
  'delay',
  'delete the first letter',
  'delve',
  'demigod',
  'demon',
  'demonstrate',
  'denial',
  'denim',
  'depletion',
  'desert',
  'deserter',
  'designer',
  'despair',
  'destroy',
  'detain',
  'determine',
  'dethrone',
  'devil',
  'devoid',
  'devotion',
  'devour',
  'dice',
  'did',
  'die',
  'difference',
  'different',
  'differently',
  'dihada',
  'dinobot',
  'dinosaur',
  'direction',
  'directly',
  'discard',
  'distance',
  'distribute',
  'disturb',
  'divide',
  'divinity',
  'djinn',
  'do',
  'dog',
  'dominaria',
  'domri',
  'done',
  'donkey',
  'doodle',
  'doom',
  'double',
  'dovin',
  'down',
  'draft',
  'dragon',
  'drake',
  'draw',
  'dreadnought',
  'dream',
  'dredge',
  'drink',
  'drone',
  'drop',
  'druid',
  'dryad',
  'duck',
  'dungeon',
  'duplication',
  'during',
  'dwarf',
  'e',
  'each',
  'earth',
  'eating',
  'echo',
  'effect',
  'efreet',
  'egg',
  'either',
  'elbow',
  'elder',
  'eldrazi',
  'elemental',
  'elephant',
  'elf',
  'elixir',
  'elk',
  'ellywick',
  'else',
  'elspeth',
  'embalm',
  'ember',
  'emblem',
  'emerge',
  'empty',
  'enchant',
  'enchantment',
  'encore',
  'encounter',
  'end',
  'enemy',
  'energy',
  'english',
  'enlightened',
  'enter',
  'entwine',
  'eon',
  'epic',
  'equal',
  'equilor',
  'equip',
  'equipment',
  'ergamon',
  'errata',
  'escalate',
  'escape',
  'estrid',
  'eternalize',
  'etherium cell',
  'even',
  'evenly',
  'ever',
  'every',
  'everything',
  'evoke',
  'evolve',
  'exactly',
  'exalted',
  'except',
  'excess',
  'exchange',
  'exert',
  'exile',
  'exist',
  'expansion',
  'experience',
  'exploit',
  'explore',
  'extort',
  'extra',
  'eye',
  'eyeball',
  'eyestalk',
  'fabacin',
  'fabricate',
  'face',
  'fact',
  'fade',
  'faerie',
  'falls',
  'far',
  'fate',
  'fateseal',
  'fear',
  'feather',
  'feet',
  'ferret',
  'fetch',
  'few',
  'fight',
  'filibuster',
  'find',
  'finger',
  'fingernail',
  'finish', # also a card name special case written up for the card that uses it.
  'finishes',
  'first',
  'fish',
  'fizzles',
  'flagbearer',
  'flame',
  'flanking',
  'flap your arms',
  'flash',
  'flashback',
  'flavor',
  'flavorful',
  'flip',
  'flood',
  'flying',
  'foe',
  'follow',
  'food',
  'foot',
  'for',
  'forehead',
  'foreshadow',
  'forest',
  'foretell',
  'fortification',
  'fortify',
  'found',
  'fox',
  'fractal',
  'free',
  'freyalise',
  'friend',
  'friends forever',
  'frog',
  'from',
  'frost',
  'full',
  'fun',
  'fungus',
  'funk',
  'fuse',
  'gain',
  'game',
  'gamer',
  'gargoyle',
  'garruk',
  'gate',
  'gem',
  'gender',
  'generic',
  'germ',
  'get',
  'ghostform',
  'giant',
  'gideon',
  'gift',
  'give',
  'glyph',
  'gnoll',
  'gnome',
  'go',
  'goad',
  'goat',
  'goblin explosioneers',
  'goblin',
  'god',
  'gold',
  'golem',
  'gorgon',
  'gorilla',
  'gotcha!',
  'grace',
  'graft',
  'grandchild',
  'grave',
  'graveborn',
  'graveyard',
  'great',
  'greed',
  'green',
  'gremlin',
  'griffin',
  'grist',
  'growl',
  'growth',
  'guess',
  'gus',
  'guy',
  'had',
  'hag',
  'half',
  'halfling',
  'hamster',
  'hand',
  'harmony',
  'harpy',
  'harvest',
  'has',
  'haste',
  'hatching',
  'hatchling',
  'hatificer',
  'hats',
  'haunt',
  'have a staring contest',
  'have',
  'he',
  'head to askurza.com and click',
  'head',
  'heads',
  'healing',
  'height',
  'held',
  'hellion',
  'her',
  'hero',
  'hexproof',
  'hidden',
  'hide',
  'hideaway',
  'high',
  'high-5',
  'him',
  'himself',
  'hippo',
  'hippogriff',
  'his',
  'historic',
  'hit', # also has a card of the same name.
  'hits',
  'hokey pokey',
  'homage',
  'homarid',
  'homelands',
  'homunculus',
  'hone',
  'hoofprint',
  'hornet',
  'horror',
  'horse',
  'horsemanship',
  'host',
  'hounds',
  'hour',
  'hourglass',
  'how',
  'huatli',
  'human',
  'hunger',
  'hydra',
  'hyena',
  'ice',
  'identity',
  'if',
  'ignore',
  'illegal',
  'illusion',
  'immediately',
  'imp',
  'improvise',
  'in a deep, booming voice, “Presenting … ”',
  'in',
  'incarnation',
  'inches',
  'include',
  'increase',
  'indestructible',
  'indicated',
  'infect',
  'infection',
  'ingest',
  'inkling',
  'innistrad',
  'insect',
  'install',
  'instance',
  'instant',
  'instead',
  'insult',
  'interplanar',
  'intervention',
  'intimidate',
  'into',
  'investigate',
  'invitation',
  'inzerva',
  'iquatana',
  'is',
  'island',
  'isolation',
  'it',
  'item',
  'itself',
  'jace',
  'jackal',
  'javelin',
  'jaya',
  'jellyfish',
  'jeska',
  'judgment',
  'juggernaut',
  'jump-start',
  'just',
  'kaito',
  'kaldheim',
  'kamigawa',
  'kangaroo',
  'karn',
  'karsus',
  'kasmina',
  'kavu',
  'kaya',
  'kephalai',
  'key',
  'keyword',
  'khans',
  'ki',
  'kick',
  'kill',
  'killbot',
  'kind',
  'kinshala',
  'kiora',
  'kirin',
  'kithkin',
  'knight',
  'knocked',
  'knowledge',
  'kobold',
  'kolbahan',
  'koni and richard continue the game and play all games as partners forever.',
  'kor',
  'koth',
  'kraken',
  'kyneth',
  'label',
  'lady of proper etiquette',
  'lair',
  'lamia',
  'lammasu',
  'land',
  'landmark',
  'large',
  'last',
  'latest mythic championship',
  'laughs',
  'league of dastardly doom',
  'learn',
  'least',
  'leave',
  'leech',
  'left',
  'leg',
  'legal',
  'legend',
  'legendary',
  'less',
  'lesson',
  'lethal',
  'letter',
  'level',
  'leviathan',
  'lhurgoyf',
  'library',
  'licid',
  'life',
  'lifelink',
  'like',
  'likewise',
  'liliana',
  'line',
  'living weapon',
  'lizard',
  'lobster',
  'locus',
  'lolth',
  'long',
  'look',
  'loose lips',
  'lore',
  'lorwyn',
  'lose',
  'low',
  'loyalty',
  'luck',
  'lukka',
  'lungs',
  'luvion',
  'made',
  'madness',
  'magic',
  'magnet',
  'main',
  'make',
  'mammoth',
  'mana',
  'stop',
  'manabond',
  'manifest',
  'manifestation',
  'mannequin',
  'manticore',
  'many',
  'mark',
  'mask',
  'masticore',
  'match',
  'mate',
  'matrix',
  'maximum',
  'may',
  'me',
  'meditation',
  'medium',
  'mega',
  'meld',
  'melee',
  'menace',
  'mentor',
  'mercadia',
  'mercenary',
  'merfolk',
  'metathran',
  'meter',
  'middle',
  'midnight',
  'mill',
  'mime',
  'mine',
  'minimum',
  'mining',
  'minion',
  'minotaur',
  'minus',
  'miracle',
  'mire',
  'mirran',
  'mirrodin',
  'moag',
  'mode',
  'modified',
  'modular',
  'mole',
  'monarch',
  'money',
  'monger',
  'mongoose',
  'mongseng',
  'monk',
  'monkey',
  'mono',
  'monstrosity',
  'monstrous',
  'moon',
  'moonfolk',
  'mordenkainen',
  'more',
  'morph',
  'most',
  'motivate',
  'mountain',
  'mouse',
  'move',
  'mowu',
  'much',
  'mulligan',
  'multiple',
  'mummy',
  'muraganda',
  'music',
  'must',
  'muster',
  'mutant',
  'mutate',
  'myr',
  'myriad',
  'mystic',
  'mythic',
  'naga',
  'nahiri',
  'name',
  'narset',
  'natural',
  'nautalid',
  'nautilus',
  'nearest',
  'necessary',
  'neck',
  'neither',
  'nephilim',
  'nerf blaster',
  'net',
  'new',
  'newt',
  'next',
  'night',
  'nightmare',
  'nightstalker',
  'niko',
  'ninja',
  'ninjutsu',
  'nissa',
  'nixilis',
  'no',
  'noble',
  'nodes',
  'noggle',
  'nomad',
  'non',
  'none',
  'normal',
  'not',
  'note',
  'nothing',
  'number',
  'nymph',
  'octopus',
  'odd',
  'of',
  'off',
  'offer',
  'ogre',
  'oko',
  'omen',
  'on',
  'once',
  'only',
  'onto',
  'ooze',
  'open',
  'opening',
  'opponent',
  'or',
  'oracle',
  'orb',
  'orc',
  'order of the widget',
  'order',
  'ore',
  'orgg',
  'original',
  'originally',
  'other',
  'otherwise',
  'otter',
  'ouphe',
  'out',
  'outlast',
  'outside',
  'over',
  'overload',
  'own',
  'ownership',
  'ox',
  'oyster',
  'pack',
  'page',
  'paid',
  'pain',
  'pair',
  'paladin',
  'pangolin',
  'paralyzation',
  'paratrooper',
  'part',
  'partner',
  'party',
  'party',
  'pass',
  'pay',
  'peace',
  'peasant',
  'pegasus',
  'pentavite',
  'people',
  'permanent',
  'permanently',
  'permission',
  'persist',
  'person',
  'pest',
  'petal',
  'petrification',
  'phase',
  'phelddagrif',
  'phenomenon',
  'phoenix',
  'phylactery',
  'phyrexia',
  'phyrexian',
  'piece',
  'pile',
  'pilot',
  'pin',
  'pincher',
  'pink',
  'pirate',
  'place',
  'plague',
  'plains',
  'planar',
  'plane',
  'planeswalker',
  'plant',
  'play',
  'plot',
  'plus',
  'point',
  'poison',
  'polyp',
  'pool',
  'pop!',
  'populate',
  'portrait',
  'post',
  'power',
  'power-plant',
  'praetor',
  'pre',
  'wind',
  'fury',
  'cloud',
  'break',
  'broken',
  'ship',
  '"i\'m rubber, you\'re glue. everything bounces off me and sticks to you"',
  '"i\'m here."',
  'premium',
  'pressure',
  'prevent',
  'previous',
  'previously',
  'prey',
  'prince',
  'printed',
  'prism',
  'proceeding',
  'process',
  'processor',
  'produce',
  'program',
  'proliferate',
  'protection',
  'provoke',
  'prowess',
  'prowl',
  'psychosis',
  'punctuation',
  'pupa',
  'put',
  'pyrulea',
  'quality',
  'quest',
  'question',
  'queue',
  'quickly',
  'quill',
  'rabbit',
  'rabiah',
  'raccoon',
  'ral',
  'rampage',
  'random',
  'randomly',
  'ranger',
  'ransom',
  'rare',
  'rarity',
  'rat',
  'rath',
  'rather',
  'ravnica',
  're',
  'reach',
  'reads',
  'rebecca guay',
  'rebel',
  'rebound',
  'recent',
  'recently',
  'reconfigure',
  'recover',
  'red',
  'redistribute',
  'reduce',
  'refer',
  'reflect',
  'reflection',
  'refuse',
  'regatha',
  'regenerate',
  'reinforce',
  'remain',
  'reminder',
  'remove',
  'renown',
  'reorder',
  'repeat',
  'replacing',
  'replicate',
  'represent',
  'reset',
  'resolve',
  'response',
  'rest',
  'restart',
  'restricted',
  'result',
  'retrace',
  'return',
  'reveal',
  'revel',
  'reverse',
  'rhino',
  'rhyming',
  'rigger',
  'right',
  'ring or imitate a bell',
  'riot',
  'ripple',
  'rock, paper, scissors',
  'rogue',
  'roll',
  'room',
  'rotates',
  'round',
  'row',
  'rowan',
  'rule',
  'rust',
  'sable',
  'sacrifice',
  'saga',
  'saheeli',
  'said',
  'salamander',
  'same',
  'samurai',
  'samut',
  'sand',
  'saproling',
  'sarkhan',
  'satyr',
  'save',
  'say',
  'scarecrow',
  'scavenge',
  'scientist',
  'scion',
  'scorpion',
  'scout',
  'scream',
  'scroll',
  'scry',
  'sculpture',
  'sealed',
  'search',
  'seat',
  'second',
  'seconds',
  'secret',
  'secretly',
  'see',
  'seek',
  'segovia',
  'select',
  'sense',
  'sentence',
  'separate',
  'serf',
  'serpent',
  'serra',
  'servo',
  'set',
  'shade',
  'shadow',
  'shadowmoor',
  'shaman',
  'shandalar',
  'shapeshifter',
  'shard',
  'share',
  'shark',
  'she',
  'sheep',
  'shell',
  'shield',
  'shoe',
  'short',
  'voyage',
  'show',
  'shred',
  'shrine',
  'shroud',
  'shuffle',
  'sickness',
  'side',
  'sideboard',
  'sided',
  'sign',
  'silver',
  'simultaneously',
  'since',
  'sing',
  'sing',
  'single',
  'siren',
  'sitting',
  'size',
  'skeleton',
  'skin',
  'skip',
  'skulk',
  'sleep',
  'sleight',
  'slime',
  'slith',
  'sliver',
  'slug',
  'slumber',
  'small',
  'snake',
  'snow',
  'so',
  'soldier',
  'soltari',
  'some',
  'something',
  'sonata',
  'song',
  'soot',
  'sorcery',
  'sorin',
  'sorry',
  'soul',
  'soulbond',
  'soulshift',
  'source',
  'spark',
  'spawn',
  'speak',
  'spectacle',
  'specter',
  'spell',
  'spellshaper',
  'spend',
  'sphinx',
  'spider',
  'spike',
  'spirit',
  'spite',
  'splice',
  'splinter',
  'split',
  'sponge',
  'spore',
  'spring',
  'sprocket',
  'sprout',
  'spy',
  'square',
  'squid',
  'squirrel',
  'squirrellink',
  'stack',
  'stakes',
  'stand',
  'starfish',
  'staring',
  'start',
  'state-based',
  'steal',
  'step',
  'stick',
  'still',
  'stone',
  'stops',
  'storage',
  'storm',
  'story',
  'straighten',
  'strength',
  'strife',
  'strike',
  'study',
  'subgame',
  'subtract',
  'summer',
  'sunburst',
  'sunrise',
  'sunset',
  'super',
  'support',
  'surge',
  'surrakar',
  'surveil',
  'survivor',
  'suspect',
  'suspend',
  'swamp',
  'swap',
  'swats',
  'switch',
  'symbol',
  'system',
  'szat',
  'table',
  'tails',
  'take',
  'tall',
  'tamiyo',
  'tap',
  'target',
  'task',
  'tasty',
  'taxes',
  'team',
  'tear',
  'teddy',
  'teferi',
  'tentacle',
  'tetravite',
  'text',
  'teyo',
  'tezzeret',
  'th',
  'thalakos',
  'than',
  'thank',
  'that',
  'the biggest, baddest, nastiest,',
  'the',
  'theft',
  'their',
  'them',
  'then',
  'there',
  'they',
  'third-degree-burn',
  'this',
  'thopter',
  'those',
  'though',
  'throw',
  'thrull',
  'tibalt',
  'tide',
  'tie',
  'tiefling',
  'time',
  'times',
  'to',
  'today',
  'together',
  'toggle',
  'token',
  'tomb of annihilation',
  'tombspawn',
  'tongue',
  'too',
  'top',
  'torture',
  'total',
  'totem armor',
  'touch',
  'toughness',
  'tower',
  'townsfolk',
  'toy',
  'train',
  'trample',
  'transfigure',
  'transform',
  'transmute',
  'trap',
  'treasure',
  'tree',
  'treefolk',
  'tribal',
  'tribute',
  'trigger',
  'trilobite',
  'triple',
  'triskelavite',
  'troll',
  'true',
  'truthfully',
  'truths',
  'turn',
  'turtle',
  'twice',
  'twin',
  'type',
  'tyvar',
  'ugin',
  'ulgrotha',
  'un',
  'undaunted',
  'under',
  'undying',
  'unicorn',
  'unique',
  'unity',
  'unleash',
  'unless',
  'until',
  'up',
  'upgrade',
  'upkeep',
  'urza',
  'use',
  'valla',
  'valor',
  'value',
  'vampire',
  'vanguard',
  'vanishing',
  'vedalken',
  'vehicle',
  'velocity',
  'venser',
  'venture',
  'verbal',
  'verse',
  'viashino',
  'vice versa',
  'vigilance',
  'ritual',
  'villain',
  'vision',
  'vitality',
  'vivien',
  'voice',
  'void',
  'volcano',
  'volley',
  'volver',
  'vortex',
  'vote',
  'vow',
  'vraska',
  'vryn',
  'wage',
  'waiter',
  'walk',
  'wall',
  'war',
  'ward',
  'warlock',
  'warrior',
  'was',
  'wasp',
  'wastes',
  'watermark',
  'way',
  'wayne england',
  'wearing',
  'web',
  'weird',
  'were',
  'werewolf',
  'whack',
  'whale',
  'whammy',
  'what',
  'when',
  'whenever',
  'where',
  'whether',
  'which',
  'whichever',
  'while',
  'whisper',
  'white',
  'who',
  'whole',
  'whom',
  'whose',
  'wild',
  'will',
  'win',
  'winter',
  'wish',
  'with',
  'wither',
  'wizard',
  'wolf',
  'wolverine',
  'wombat',
  'women',
  'word',
  'wordy',
  'world',
  'worm',
  'worn',
  'would',
  'wraith',
  'wrenn',
  'wrestle', # UN
  'write',
  'written',
  'wrong',
  'wurm',
  'x',
  'xenagos',
  'xerex',
  'y',
  'yanggu',
  'yanling',
  'year',
  'yet',
  'yeti',
  'you',
  'your',
  'z',
  'zariel',
  'zendikar',
  'zombie',
  'zone',
  'zubera',
  '|',
  '~',
  '~~',
  'π',
  '—',
  '—',
  '•',
  '∞',
  '☐',
)

## TODO
# Everything from atinlay igpay except name

# if the left matches replace with the right. Priority over token matching.
extra_productions: tuple[tuple[str, tuple[str, ...]], ...] = (
  (' ', ()),
  ('abilities', ('ability', '##s')),
  ('accepted', ('accept', '##ed')),
  ('acrificesay', ('sacrifice',)),
  ('actions', ('action', '##s')),
  ('19½', ('19', '.5',)),
  ('activated', ('activate', '##ed')),
  ('activates', ('activate', '##vs')),
  ('activating', ('activate', '##ing')),
  ('adapts', ('adapt', '##vs')),
  ('added', ('add', '##ed')),
  ('adds', ('add', '##vs')),
  ('advisors', ('advisor', '##s')),
  ('allies', ('ally', '##s')),
  ('amassed', ('amass', '##ed')),
  ('an', ('a',)),
  ('angels', ('angel', '##s')),
  ('answer', ('answer', '##vs')),
  ('antes', ('ante', '##vs')),
  ('apes', ('ape', '##s')),
  ('arcane—', ('arcane',)),
  ("aren't", ('are', 'not',)),
  ('arm-wrestle', ('arm', 'wrestle')),
  ('arms', ('arm', '##s')),
  ('artifacts', ('artifact', '##s')),
  ('ascended', ('ascend', '##ed')),
  ('asking', ('ask', '##ing')),
  ('asks', ('ask', '##vs')),
  ('assembles', ('assemble', '##vs')),
  ('assigned', ('assign', '##ed')),
  ('assigns', ('assign', '##vs')),
  ('attached', ('attach', '##ed')),
  ('attaches', ('attach', '##s')),
  ('fifteen', ('15',)),
  ('attacked', ('attack', '##ed')),
  ('attacker', ('attack', '##er')),
  ('attacking', ('attack', '##ing')),
  ('attacks', ('attack', '##vs')),
  ('auras', ('aura', '##s')),
  ('balanced', ('balance', '##ed')),
  ('balances', ('balance', '##vs')),
  ('banded', ('band', '##ed')),
  ('banding', ('band', '##ing')),
  ('bands', ('band', '##s')),
  ('banned', ('ban', '##ed')),
  ('bats', ('bat', '##s')),
  ('beasts', ('beast', '##s')),
  ('became', ('become', '##ed')),
  ('becomes', ('become', '##s')),
  ('becoming', ('become', '##ing')),
  ('beebles', ('beeble', '##s')),
  ('begain', ('begin', '##ed')),
  ('beginning', ('begin', '##ing')),
  ('bidder', ('bid', '##er')),
  ('bidding', ('bid', '##ing')),
  ('birds', ('bird', '##s')),
  ('black-bordered', ('black', 'border', '##ed')),
  ('blocked', ('block', '##ed')),
  ('blockers', ('block', '##er', '##s')),
  ('blocking', ('block', '##ing')),
  ('blocks', ('block', '##s')),
  ('borders', ('border', '##s')),
  ('brainiacs', ('brainiac', '##s')),
  ('buyback—', ('buyback',)),
  ('camarids', ('camarid', '##s')),
  ('twelve', ('12',)),
  ('thirteen', ('13',)),
  ('cannot', ('can', 'not')),
  ('cards', ('card', '##s')),
  ('casting', ('cast', '##ing')),
  ('casts', ('cast', '##vs')),
  ('catches', ('catch', '##vs')),
  ('cats', ('cat', '##s')),
  ('causes', ('cause', '##vs')),
  ('cephalids', ('cephalid', '##s')),
  ('championed', ('champion', '##ed')),
  ('changed', ('change', '##ed')),
  ('changing', ('change', '##ing')),
  ('choices', ('choice', '##s')),
  ('chooses', ('choose', '##vs')),
  ('choosing', ('choose', '##ing')),
  ('chose', ('choose', '##ed')),
  ('one and one-half', ('1', '.5')),
  ('²', ('square', '##ed',)),
  ('clerics', ('cleric', '##s')),
  ('clues', ('clue', '##s')),
  ('coins', ('coin', '##s')),
  ('colored', ('color', '##ed')),
  ('colorless', ('not', 'color', '##ed')),
  ('colors', ('color', '##s')),
  ('combined', ('combine', '##ed')),
  ('comes', ('come', '##vs')),
  ('coming', ('come', '##ing')),
  ('commanders', ('commander', '##s')),
  ('completed', ('complete', '##ed')),
  ("pursuant to subsection 3.1 of richard's rules of order, at the beginning of the upkeep of each participant in this game of the magic: the gathering trading card game , that player performs all actions in the sequence of previously added actions , in the order those actions were added, then adds another action to the end of the action queue. all actions must be simple physical or verbal actions that a player can perform while sitting in a chair, without jeopardizing the health and security of said player.", ('[[bureaucracy]]',)),
  ('any player', ('a', 'play', '##er')),
  ('does not perform all the prescribed actions in the correct order', ('[[bureaucracycond]]',)),
  ('said player', ('that', 'play', '##er',)),
  ('complement of cards in hand', ('hand',)),
  ('contraptions', ('contraption', '##s')),
  ('controlled', ('control', '##ed')),
  ('controller', ('control', '##er')),
  ('controls', ('control', '##vs')),
  ('converted mana cost', ('mana', 'value')),
  ('convoked', ('convoke', '##ed')),
  ('copied', ('copy', '##ed')),
  ('copies', ('copy', '##s')),
  ('copying', ('copy', '##ing')),
  ('costs', ('cost', '##s')),
  ("couldn't", ('could', 'not')),
  ('counters', ('counter', '##s')),
  ('countered', ('counter', '##ed')),
  ('covered', ('cover', '##ed')),
  ('covering', ('cover', '##ing')),
  ('cowards', ('coward', '##s')),
  ('crabs', ('crab', '##s')),
  ('creates', ('create', '##vs')),
  ('created', ('create', '##ed')),
  ('creatures', ('creature', '##s')),
  ('crews', ('crew', '##vs')),
  ('crewed', ('crew', '##ed')),
  ('curses', ('curse', '##s')),
  ('cycles', ('cycle', '##vs')),
  ('cycled', ('cycle', '##ed')),
  ('cycling', ('cycle', '##ing')),
  ('cycling—', ('cycle', '##ing')),
  ('d20', ('20', 'sided', 'dice')),
  ('d10', ('10', 'sided', 'dice')),
  ('d12', ('12', 'sided', 'dice')),
  ('d4', ('4', 'sided', 'dice')),
  ('d6', ('6', 'sided', 'dice')),
  ('d8', ('8', 'sided', 'dice')),
  ('deals', ('deal', '##vs')),
  ('dealt', ('deal', '##ed')),
  ('decides', ('decide', '##vs')),
  ('decks', ('deck', '##s')),
  ('declared', ('declare', '##ed')),
  ('declaring', ('declare', '##ing')),
  ('demons', ('demon', '##s')),
  ('deserts', ('desert', '##s')),
  ('destroyed', ('destroy', '##ed')),
  ('destroys', ('destroy', '##vs')),
  ('determined', ('determine', '##ed')),
  ('devils', ('devil', '##s')),
  ('devoured', ('devour', '##ed')),
  ("didn't", ('did', 'not')),
  ('died', ('die', '##ed')),
  ('dies', ('die', '##vs')),
  ('dinosaurs', ('dinosaur', '##s')),
  ('discarded', ('discard', '##ed')),
  ('discarding', ('discard', '##ing')),
  ('discards', ('discard', '##vs')),
  ('distributes', ('distribute', '##vs')),
  ('divides', ('divide', '##vs')),
  ('divided', ('divide', '##ed')),
  ('djinns', ('djinn', '##s')),
  ('does', ('do', '##vs')),
  ("doesn't", ('do', '##vs', 'not')),
  ('dogs', ('dog', '##s')),
  ('doing', ('do', '##ing')),
  ("don't", ('do', 'not')),
  ('doubles', ('double', '##vs')),
  ('drafted', ('draft', '##ed')),
  ('drafting', ('draft', '##ing')),
  ('drafts', ('draft', '##vs')),
  ('dragons', ('dragon', '##s')),
  ('drawing', ('draw', '##ing')),
  ('drawn', ('draw', '##er')),
  ('draws', ('draw', '##vs')),
  ('drew', ('draw', '##ed')),
  ('dropped', ('drop', '##ed')),
  ('druids', ('druid', '##s')),
  ('dungeons', ('dungeon', '##s')),
  ('dwarves', ('dwarf', '##s')),
  ('dying', ('die', '##ing')),
  ('eaturecraw', ('creature',)),
  ('echo—', ('echo',)),
  ('effects', ('effect', '##s')),
  ('efreets', ('efreet', '##s')),
  ('eight', ('8',)),
  ('elementals', ('elemental', '##s')),
  ('elves', ('elf', '##s')),
  ('embalmed', ('embalm', '##ed')),
  ('emblems', ('emblem', '##s')),
  ('enchanted', ('enchant', '##ed')),
  ('enchanting', ('enchant', '##ing')),
  ('enchantments', ('enchantment', '##s')),
  ('ended', ('end', '##ed')),
  ('ending', ('end', '##ing')),
  ('ends', ('end', '##vs')),
  ('enemy-colored', ('enemy', 'color', '##ed')),
  ('entered', ('enter', '##ed')),
  ('entering', ('enter', '##ing')),
  ('enters', ('enter', '##vs')),
  ('entwine—', ('entwine',)),
  ('enwhay', ('when',)),
  ('equipped', ('equip', '##ed')),
  ('equip—', ('equip',)),
  ('escalate—', ('escalate',)),
  ('escapes', ('escape', '##vs')),
  ('escaped', ('escape', '##ed')),
  ('eternalize—', ('eternalize',)),
  ('evoke—', ('evoke',)),
  ('evolves', ('evolve', '##vs')),
  ('exchanged', ('exchange', '##ed')),
  ('exerted', ('exert', '##ed')),
  ('exiled', ('exile', '##ed')),
  ('exiles', ('exile', '##vs')),
  ('exiling', ('exile', '##ing')),
  ('expansion-symbol', ('expansion', 'symbol')),
  ('exploits', ('exploit', '##vs')),
  ('exploited', ('exploit', '##ed')),
  ('explores', ('explore', '##vs')),
  ('eyes', ('eye', '##s')),
  ('face-down', ('face', 'down')),
  ('face-up', ('face', 'up')),
  ('facing', ('face', '##ing')),
  ('fading', ('fade', '##ing')),
  ('faeries', ('faerie', '##s')),
  ('fewer', ('few', '##er')),
  ('fewest', ('few', '##est')),
  ('fights', ('fight', '##vs')),
  ('fingers', ('finger', '##s')),
  ('finish voting', ('finish', 'vote', '##ing')),
  ('five', ('5',)),
  ('firstest', ('1', 'th', '##est')),
  ('flashback—', ('flashback',)),
  ('flipped', ('flip', '##ed')),
  ('flipping', ('flip', '##ing')),
  ('flips', ('flip', '##s')),
  ('followed', ('follow', '##ed')),
  ('following', ('follow', '##ing')),
  ('foods', ('food', '##s')),
  ('forests', ('forest', '##s')),
  ('foretelling', ('foretell', '##ing')),
  ('foretold', ('foretell', '##ed')),
  ('fortified', ('fortify', '##ed')),
  ('four', ('4',)),
  ('fourth', ('4', 'th')),
  ('gained', ('gain', '##ed')),
  ('gains', ('gain', '##vs')),
  ('games', ('game', '##s')),
  ('gates', ('gate', '##s')),
  ('gets', ('get', '##vs')),
  ('giants', ('giant', '##s')),
  ('goaded', ('goad', '##ed')),
  ('goats', ('goat', '##s')),
  ('goblins', ('goblin', '##s')),
  ('golems', ('golem', '##s')),
  ('gorgons', ('gorgon', '##s')),
  ('graveyards', ('graveyard', '##s')),
  ('greater', ('great', '##er')),
  ('greatest', ('great', '##est')),
  ('w', ('white',)),
  ('u', ('blue',)),
  ('b', ('black',)),
  ('r', ('red',)),
  ('g', ('green',)),
  ('c', ('not', 'color', '##ed')),
  ('s', ('snow',)),
  ('p', ('phyrexian',)),
  ('t', ('tap',)),
  ('q', ('un', 'tap')),
  ('gremlins', ('gremlin', '##s')),
  ('guesses', ('guess', '##vs')),
  ('guessed', ('guess', '##ed')),
  ("hadn't", ('had', 'not')),
  ('hands', ('hand', '##s')),
  ("hasn't", ('has', 'not')),
  ('haunted', ('haunt', '##ed')),
  ('haunting', ('haunt', '##ing')),
  ('haunts', ('haunt', '##vs')),
  ("haven't", ('have', 'not')),
  ('having', ('have', '##ing')),
  ('hides', ('hide', '##vs')),
  ('high-fives', ('high-5', '##s')),
  ('higher', ('high', '##er')),
  ('highest', ('high', '##est')),
  ('hit counter', ('hit', 'counter')),
  ('homarids', ('homarid', '##s')),
  ('horses', ('horse', '##s')),
  ('humans', ('human', '##s')),
  ('ikestray', ('strike',)),
  ('illusions', ('illusion', '##s')),
  ('including', ('include', '##ing')),
  ('increased', ('increase', '##ed')),
  ('inklings', ('inkling', '##s')),
  ('insects', ('insect', '##s')),
  ('instances', ('instance', '##s')),
  ('instants', ('instant', '##s')),
  ('investigated', ('investigate', '##ed')),
  ('investigates', ('investigate', '##vs')),
  ('islands', ('island', '##s')),
  ("isn't", ('is', 'not')),
  ('items', ('item', '##s')),
  ('its', ('it', "'s")),
  ("it's", ('it', 'is')),
  ('kicker', ('kick', '##er')),
  ('kicked', ('kick', '##ed')),
  ('kicker—', ('kick', '##er')),
  ('kicks', ('kick', '##vs')),
  ('kinds', ('kind', '##s')),
  ('knights', ('knight', '##s')),
  ('did you know this creature has flying?', ('flying',)),
  ('kobolds', ('kobold', '##s')),
  ('krakens', ('kraken', '##s')),
  ('lands', ('land', '##s')),
  ('leaves', ('leave', '##vs')),
  ('leaving', ('leave', '##ing')),
  ('legs', ('leg', '##s')),
  ('lesser', ('less', '##er')),
  ('letters', ('letter', '##s')),
  ('leviathans', ('leviathan', '##s')),
  ('libraries', ('library', '##s')),
  ('line', ('line', '##s')),
  ('longer', ('long', '##er')),
  ('longest', ('long', '##est')),
  ('looked', ('look', '##ed')),
  ('looks', ('look', '##s')),
  ('loses', ('lose', '##vs')),
  ('losing', ('lose', '##ing')),
  ('lost', ('lose', '##ed')),
  ('lower',  ('low', '##er')),
  ('lowest', ('low', '##est')),
  ('madness—', ('madness',)),
  ('makes', ('make', '##vs')),
  ('manifested', ('manifest', '##ed')),
  ('manifests', ('manifest', '##vs')),
  ('marks', ('mark', '##vs')),
  ('marked', ('mark', '##ed')),
  ('mercenaries', ('mercenary', '##s')),
  ('meters', ('meter', '##s')),
  ('milled', ('mill', '##ed')),
  ('mills', ('mill', '##vs')),
  ('modes', ('mode', '##s')),
  ('modular—', ('modular',)),
  ('morph—', ('morph',)),
  ('mountains', ('mountain', '##s')),
  ('moves', ('move', '##vs')),
  ('moved', ('move', '##ed')),
  ('mulligans', ('mulligan', '##s')),
  ('multi', ('multiple',)),
  ('mutated', ('mutate', '##ed')),
  ('mutates', ('mutate', '##vs')),
  ('named', ('name', '##ed')),
  ('names', ('name', '##s')),
  ('nautilids', ('nautalid', '##s')),
  ('nightmares', ('nightmare', '##s')),
  ('nine', ('9',)),
  ('ninety-9', ('99',)),
  ('ninjas', ('ninja', '##s')),
  ('nor', ('not', 'or')),
  ('noted', ('note', '##ed')),
  ('numeral', ('number',)),
  ('numbers', ('number', '##s')),
  ('octopuses', ('octopus', '##s')),
  ('offering', ('offer', '##ing')),
  ('oozes', ('ooze', '##s')),
  ('opponents', ('opponent', '##s')),
  ('orcs', ('orc', '##s')),
  ('oubleday', ('double',)),
  ('ouyay', ('you',)),
  ('owned', ('own', '##ed')),
  ('owner', ('own', '##er')),
  ('owners', ('own', '##er', '##s')),
  ('owns', ('own', '##vs')),
  ('packs', ('pack', '##s')),
  ('paired', ('pair', '##ed')),
  ('passed', ('pass', '##ed')),
  ('passes', ('pass', '##vs')),
  ('paying', ('pay', '##ing')),
  ('pays', ('pay', '##vs')),
  ('permanents', ('permanent', '##s')),
  ('pests', ('pest', '##s')),
  ('phased', ('phase', '##ed')),
  ('phased-out', ('phase', '##ed', 'out')),
  ('phases', ('phase', '##vs')),
  ('phasing', ('phase', '##ing')),
  ('pieces', ('piece', '##s')),
  ('piles', ('pile', '##s')),
  ('pirates', ('pirate', '##s')),
  ('places', ('place', '##vs')),
  ('planes', ('plane', '##s')),
  ('planeswalks', ('plane', '##s', 'walk', '##vs')),
  ('planeswalkers', ('planeswalker', '##s')),
  ('player', ('play', '##er')),
  ('players', ('play', '##er', '##s')),
  ('playings', ('play', '##ing')),
  ('plays', ('play', '##vs')),
  ('played', ('play', '##ed')),
  ('points', ('point', '##vs')),
  ('poisoned', ('poison', '##ed')),
  ('poisonous', ('poison', '##er')),
  ('pools', ('pool', '##s')),
  ('powers', ('power', '##s')),
  ('prevented', ('prevent', '##ed')),
  ('produced', ('produce', '##ed')),
  ('produces', ('produce', '##vs')),
  ('puts', ('put', '##vs')),
  ('putting', ('put', '##ing')),
  ('questions', ('question', '##s')),
  ('random—', ('random',)),
  ('rats', ('rat', '##s')),
  ('rebels', ('rebel', '##s')),
  ('recover—pay', ('recover',)),
  ('reduced', ('reduce', '##ed')),
  ('reduces', ('reduce', '##vs')),
  ('refers', ('refer', '##vs')),
  ('reflections', ('reflection', '##s')),
  ('regenerated', ('regenerate', '##ed')),
  ('regenerates', ('regenerate', '##vs')),
  ('remains', ('remain', "##s")),
  ('removed', ('remove', '##ed')),
  ('removes', ('remove', '##vs')),
  ('renowned', ('renown', '##ed')),
  ('repeats', ('repeat', '##vs')),
  ('replicated', ('replicate', '##ed')),
  ('representing', ('represent', '##ing')),
  ('resets', ('reset', '##vs')),
  ('resolved', ('resolve', '##ed')),
  ('resolved', ('resolve', '##vs')),
  ('resolving', ('resolve', '##ing')),
  ('results', ('result', '##s')),
  ('returned', ('return', '##ed')),
  ('returns', ('return', '##vs')),
  ('revealed', ('reveal', '##ed')),
  ('revealing', ('reveal', '##ing')),
  ('reveals', ('reveal', '##vs')),
  ('reversed', ('reverse', '##ed')),
  ('riggers', ('rigger', '##s')),
  ('rogues', ('rogue', '##s')),
  ('rolled', ('roll', '##ed')),
  ('rolls', ('roll', '##vs')),
  ('rounded', ('round', '##ed')),
  ('rules', ('rule', '##s')),
  ('sacrificed', ('sacrifice', '##ed')),
  ('sacrifices', ('sacrifice', '##vs')),
  ('sacrificing', ('sacrifice', '##ing')),
  ('salamanders', ('salamander', '##s')),
  ('sang', ('sing', '##ed')),
  ('saprolings', ('saproling', '##s')),
  ('satyrs', ('satyr', '##s')),
  ('says', ('say', '##vs')),
  ('scavenger', ('scavenge', '##er')),
  ('scavengers', ('scavenge', '##er', '##s')),
  ('scavenging', ('scavenge', '##ing')),
  ('scions', ('scion', '##s')),
  ('sculptures', ('sculpture', '##s')),
  ('searched', ('search', '##ed')),
  ('searches', ('search', '##vs')),
  ('searching', ('search', '##ing')),
  ('seated', ('seat', '##ed')),
  ('sentences', ('sentence', '##s')),
  ('separates', ('separate', '##vs')),
  ('serpents', ('serpent', '##s')),
  ('servos', ('servo', '##s')),
  ('shamans', ('shaman', '##s')),
  ('shapeshifters', ('shapeshifter', '##s')),
  ('shares', ('share', '##vs')),
  ('shared', ('share', '##ed')),
  ('shoes', ('shoe', '##s')),
  ('shorter', ('short', '##er')),
  ('showing', ('show', '##ing')),
  ('shrines', ('shrine', '##s')),
  ('shuffled', ('shuffle', '##ed')),
  ('shuffles', ('shuffle', '##vs')),
  ('shuffling', ('shuffle', '##ing')),
  ('silver-bordered', ('silver', 'border', '##ed')),
  ('six', ('6',)),
  ('-sided die', ('sided', 'dice')),
  ('skeletons', ('skeleton', '##s')),
  ('skips', ('skip', '##s')),
  ('slivers', ('sliver', '##s')),
  ('smaller', ('small', '##er')),
  ('snakes', ('snake', '##s')),
  ('snow-covered', ('snow', 'cover', '##ed')),
  ('soldiers', ('soldier', '##s')),
  ('sorceries', ('sorcery', '##s')),
  ('sources', ('source', '##s')),
  ('spells', ('spell', '##s')),
  ('spent', ('spend', '##ed')),
  ('spirits', ('spirit', '##s')),
  ('spiders', ('spider', '##s')),
  ('spliced', ('splice', '##ed')),
  ('squirrels', ('squirrel', '##s')),
  ('standing', ('stand', '##ing')),
  ('started', ('start', '##ed')),
  ('starting', ('start', '##ing')),
  ('starts', ('start', '##s')),
  ('steals', ('steal', '##vs')),
  ('steps', ('step', '##s')),
  ('stops', ('stop', '##vs')),
  ('stuck', ('stick', '##ed')),
  ('summon', ('creature', '—')),
  ('surveilled', ('surveil', '##ed')),
  ('survivors', ('survivor', '##s')),
  ('suspended', ('suspend', '##ed')),
  ('swamps', ('swamp', '##s')),
  ('symbols', ('symbol', '##s')),
  ('taken', ('take', '##er')),
  ('takes', ('take', '##vs')),
  ('taking', ('take', '##ing')),
  ('taller', ('tall', '##er')),
  ('tapped', ('tap', '##ed')),
  ('taps', ('tap', '##vs')),
  ('targeted', ('target', '##ed')),
  ('targets', ('target', '##s')),
  ('mates', ('mate', '##s')),
  ('ten', ('10',)),
  ('third', ('3', 'th')),
  ('thirteen', ('13',)),
  ('seventh', ('7', 'th')),
  ('thopters', ('thopter', '##s')),
  ('thrulls', ('thrull', '##s')),
  ('thrown', ('throw', '##er')),
  ('tied', ('tie', '##ed')),
  ('ties', ('tie', '##vs')),
  ('tokens', ('token', '##s')),
  ('totals', ('total', '##vs')),
  ('touched', ('touch', '##ed')),
  ('touches', ('touch', '##vs')),
  ('touching', ('touch', '##ing')),
  ('training', ('train', '##ing')),
  ('trains', ('train', '##vs')),
  ('transformed', ('transform', '##ed')),
  ('transformers', ('transform', '##er', '##s')),
  ('transforms', ('transform', '##s')),
  ('treasures', ('treasure', '##s')),
  ('triggered', ('trigger', '##ed')),
  ('triggers', ('trigger', '##vs')),
  ('turns', ('turn', '##s')),
  ('turned', ('turn', '##ed')),
  ('twelfth', ('12', 'th')),
  ('twenty', ('20',)),
  ('two', ('2',)),
  ('types', ('type', '##s')),
  ('opened', ('open', '##ed')),
  ('upkeeps', ('upkeep', '##s')),
  ('upkeep—', ('upkeep',)),
  ('uses', ('use', '##vs')),
  ('using', ('use', '##ing')),
  ('values', ('value', '##s')),
  ('challenged', ('challenge', '##ed')),
  ('vampires', ('vampire', '##s')),
  ('vampyre', ('vampire',)),
  ('vehicles', ('vehicle', '##s')),
  ('voted', ('vote', '##ed')),
  ('voter', ('vote', '##er')),
  ('votes', ('vote', '##s')),
  ('voting', ('vote', '##ing')),
  ('walls', ('wall', '##s')),
  ('ward—', ('ward',)),
  ('warriors', ('warrior', '##s')),
  ("wasn't", ('was', 'not')),
  ('watermarks', ('watermark', '##s')),
  ("weren't", ('were', 'not')),
  ('werewolves', ('werewolf', '##s')),
  ('white-bordered', ('white', 'border', '##ed')),
  ('winner', ('win', '##er')),
  ('winning', ('win', '##ing')),
  ('wins', ('win', '##s')),
  ('wizards', ('wizard', '##s')),
  ('wolves', ('wolf', '##s')),
  ('won', ('win', '##ed')),
  ('words', ('word', '##s')),
  ('wrestler', ('wrestle', '##er')),
  ('years', ('year', '##s')),
  ('yes-or-no', ('yes', 'or', 'no')),
  ("you'll", ('you', 'will')),
  ("you've", ('you', 'have')),
  ('zero', ('0',)),
  ('zombies', ('zombie', '##s')),
  ('zones', ('zone', '##s')),
  ('nonenchantment', ('non', 'enchantment')),
  ('½', ('.5',)),
  ('eleven', ('11',)),
  ("they've", ('they', 'have')),
  ('non-', ('non',)),
  ('represented', ('represent', '##ed')),
  ('igpay', ('pig',)),
  ('eakspay', ('speak',)),
  ('ordway', ('word',)),
  ('fourteen', ('14',)),
  ('thirty', ('30',)),
  ('stoned', ('stone', '##ed')),
)

# Replace with ~~. Priority over extra_productions
referenced_card_names: tuple[str, ...] = (
  'alpine watchdog',
  'sorin, vampire lord',
  'festering goblin',
  "vivien, nature's avenger",
  'vraska, regal gorgon',
  'hammer of ~',
  '~\'s pridemate',
  'ajani, inspiring leader',
  'oko, the trickster',
  'butterfly',
  'smoke blessing',
  'keeper of ~',
  'urami',
  'wood',
  'liliana, death mage',
  'ecstatic piper',
  'liliana, death wielder',
  'empyrial archangel',
  "nissa, nature's artisan",
  'ashaya, the awoken world',
  'hammer of nazahn',
  'karox bladewing',
  'ignorant bliss',
  'crack the earth',
  'blazing volley',
  'seething song',
  'dance with devils',
  'flamebreak',
  'hellion eruption',
  'insurrection',
  'warp world',
  'bogbrew witch',
  'kobolds of kher keep',
  'chandra, bold pyromancer',
  'lightning bolt',
  'land mine',
  'boo',
  'the underworld cookbook',
  'disenchant',
  'braingeyser',
  'terror',
  'shivan dragon',
  'regrowth',
  'black lotus',
  'brambleweft behemoth',
  'nissa, genesis mage',
  'breathstealer',
  'feral shadow',
  "bride's gown",
  'bruna, the fading light',
  'brisela, voice of nightmares',
  'festering newt',
  'bubbling cauldron',
  'ral, caller of storms',
  'carnivore',
  "chandra, flame's catalyst",
  'mu yanling, celestial wind',
  'chittering host',
  'cloud sprite',
  "koma's coil",
  'crown of empires',
  'throne of empires',
  'nicol bolas, the deceiver',
  'peer through depths',
  'sift through sands',
  'the unspeakable',
  'basri, devoted paladin',
  'heart-piercer bow',
  'vial of dragonfire',
  'mulldrifter',
  'scepter of empires',
  'throne of empires',
  'crown of empires',
  'rowan, fearless sparkmage',
  'ashiok, sculptor of fears',
  'guan yu, sainted warrior',
  'zhang fei, fierce warrior',
  'rahilda, feral outlaw',
  "groom's finery",
  'hanweir garrison',
  "god-pharaoh's gift",
  'godsire',
  'goldmeadow harrier',
  'guenhwyvar',
  'gunk',
  'halvar, god of battle',
  'sword of kaldra',
  'shield of kaldra',
  'helm of kaldra',
  'garruk, savage herald',
  'elspeth, undaunted hero',
  'sunlit hoplite',
  'wolves of the hunt',
  'icy manalith',
  'igneous cur',
  'jace, ingenious mind-mage',
  'ajani, aspiring leader',
  'jiang yanggu',
  'keimi',
  'kelp',
  'keeper of kookus',
  'labyrinth of skophos',
  'marit lage',
  'dovin, architect of law',
  'lumbering lightshield',
  'lightning rager',
  'llanowar elves',
  'gideon, martial paragon',
  'tezzeret, master of metal',
  'mechtitan',
  'land mine',
  'metallic sliver',
  'minor demon',
  'missile',
  'mu yanling',
  'gideon, the oathsworn',
  'muscle burst',
  "tamiyo's notebook",
  'paper tiger',
  'pacifism',
  "ajani's pridemate",
  'prince of thralls',
  'ajani, valiant protector',
  'chandra, pyrogenius',
  'rabid sheep',
  'ragavan',
  'rampant growth',
  'giant growth',
  'regrowth',
  'regal force',
  'rock',
  'vraska, scheming gorgon',
  'spitting drake',
  'viashivan dragon',
  'stoneforged blade',
  'scissors lizard',
  'teferi, timebender',
  'teferi, timeless voyager',
  'hanweir, the writhing township',
  'tuktuk the returned',
  'reach through mists',
  'stangg twin',
  'vecna',
  'voja, friend to elves',
  'eye of vecna',
  'hand of vecna',
  'vitu-ghazi',
  'wirefly',
  'voja',
  'reassembling skeleton',
  'kaldra',
)

# Replace with ~. Priority over referenced_card_names
extra_card_names = (
  'shimatsu',
  "~'s coil",
  'volt-charged berserker',
  'tangled vale',
  'waildrifter',
  'withengar unbound',
  'vision of the unspeakable',
  'svyelun',
  'phage',
  'ruin',
  'tumble',
  'vastwood thicket',
  'jace, arcane strategist',
  'stomp',
  'trouble',
  'sphinx sovereign',
  'struggle',
  'revel in silence',
  'valakut stoneforge',
  'rashka',
  'domri, city smasher',
  'silverpelt werewolf',
  'seafaring werewolf',
  'rubinia',
  'rakdos',
  'turntimber, serpentine wood',
  'sea gate, reborn',
  'chandra, roaring flame',
  'rasputin',
  'ulvenwald primordials',
  'timber shredder',
  'scarmaker',
  'remnant of the rising star',
  "dorathea's retribution",
  'applejack',
  'fluttershy',
  'song-mad ruins',
  'sinuous predator',
  'riphook raider',
  'werewolf ransacker',
  'rampaging werewolf',
  'pinkie pie',
  'rainbow dash',
  'lord of the ulvenwald',
  'ondu skyruins',
  'wildblood pack',
  'one of the pack',
  'persistent nightmare',
  'autumn-tail, kitsune sage',
  'o-kagachi made manifest',
  'metzali, tower of triumph',
  'odious witch',
  'portrait of michiko',
  "tovolar's magehunter",
  'howling chorus',
  'moonscarred werewolf',
  'luminous phantom',
  'malakir mire',
  'merciless predator',
  'makindi mesas',
  'silundi isle',
  'grimlock, dinobot leader',
  'journey to the oracle',
  'lone wolf of the natterknolls',
  'lambholt butcher',
  'it that rides as one',
  'likeness of the seeker',
  "lanterns' lift",
  "tovolar's packleader",
  "tergrid's lantern",
  'lambholt ravager',
  'kazandu valley',
  "kazuul's cliffs",
  'khalni territory',
  'jwari ruins',
  'terror of kruin pass',
  'kaiso, memory of loyalty',
  'injury',
  'kabira plateau',
  'kirin-touched orochi',
  'jaraku the interloper',
  "sinner's judgment",
  'malicious invader',
  'ironfang',
  'lunarch inquisitors',
  'insidious mist',
  'moonrise intruder',
  'twinblade invocation',
  'ichiga, who topples oaks',
  "~'s rising dawn",
  'hit',
  'incited rabble',
  'wildsong howler',
  'krallenhorde wantons',
  'infested werewolf',
  'krallenhorde killer',
  'hivis',
  'hinterland scourge',
  'timber shredder',
  'heaven',
  'hellkite overlord',
  'shatterskull, the hammer pass',
  'hazezon',
  'hazoret',
  'havengul mystery',
  "toralf's hammer",
  'hakka, whispering raven',
  'haktos',
  'perfected form',
  'gutter shortcut',
  'goka the unjust',
  'sejiri glacier',
  'graveyard glutton',
  'generous soul',
  'ghastly mimicry',
  'gatstaf ravagers',
  'gatstaf howler',
  'unimpeded trespasser',
  "arlinn, the moon's fury",
  'furious',
  'frenzied trapbreaker',
  'fragment of konda',
  'flamethrower sonata',
  'flameheart werewolf',
  'chandra, roaring flame',
  'inherited fiend',
  'finish',
  'grimlock, ferocious king',
  'poppet factory',
  'umara skyfalls',
  'ravager of the fells',
  'fangblade eviscerator',
  'howlpack of estwald',
  'fibrous entangler',
  'emeria, shattered skyclave',
  'embodiment of flame',
  'heaven',
  "olag, ludevic's hubris",
  'earth',
  'dronepack kindred',
  'drizzt',
  'hook-haunt drifter',
  'waildrifter',
  'abolisher of bloodlines',
  'agadeem, the undercrypt',
  'akoum teeth',
  'vessel of the all-consuming',
  'vildin-pack alpha',
  'howlpack alpha',
  'ulrich, uncontested alpha',
  'dire-strain anarchist',
  'arlinn, embraced by the moon',
  "ancestor's embrace",
  'werewolf of ancient hunger',
  'angelic enforcer',
  "animus of night's reach",
  'dennick, pious apparition',
  'morning apparition',
  'archdemon of greed',
  'avacyn, the purifier',
  'architect of restoration',
  'nicol bolas the arisen',
  'drogskol armaments',
  'assault',
  'azamuki, treachery incarnate',
  'baneclaw marauder',
  'bane of hanweir',
  'bala ged sanctuary',
  'ballista wielder',
  'b.o.b',
  'ashmouth dragon',
  'aurora of emrakul',
  'howlpack avenger',
  'axelrod',
  'skyclave basilica',
  'spitfire bastion',
  'gideon, battle-forged',
  'bearer of overwhelming truths',
  'bedazzle',
  'benevolent geist',
  'beyeen coast',
  'spectral binding',
  'biolume serpent',
  'blackbloom bog',
  'fangblade eviscerator',
  'twinblade invocation',
  'zof bloodbog',
  'bloodsworn knight',
  'branch of boseiju',
  'branded howler',
  'krallenhorde howler',
  'neck breaker',
  'nightfall predator',
  'frenzied trapbreaker',
  'wrathful jailbreaker',
  'brinebound gift',
  'hagra broodpit',
  'homicidal brute',
  'burn',
  'restorative burst',
  'cackling culprit',
  'westvale cult leader',
  'carnage',
  'carnival',
  'ghostly castigator',
  'unhallowed cathar',
  "~ markov's coffin",
  'catlike curiosity',
  'catti-brie',
  'cardname',
  'pelakka caverns',
  'spikefield cave',
  'chapel shieldgeist',
  'chilling chronicle',
  'cipherbound spirit',
  'clever distraction',
  "edgar markov's coffin",
  'collision',
  'conduit of emrakul',
  'tibalt, cosmic impostor',
  'covetous geist',
  'wedding crasher',
  'creeping inn',
  'the ringhart crest',
  'crovax',
  'westvale cult leader',
  'cut',
  'deadly dancer',
  'darigaaz',
  'scion of darkness',
  'dauntless avenger',
  "katilda's rising dawn",
  'dead',
  'embrose, dean of shadow',
  'nassari, dean of expression',
  'deathbonnet hulk',
  'krothuss, lord of the deep',
  'demon-possessed witch',
  'departed soulkeeper',
  'werewolf ransacker',
  'wayward disciple',
  "dragon-kami's egg",
  'erupting dreadwolf',
  'fire',
  '~, the arisen',
  'glasspool shore',
  'tumble',
  "~'s lantern",
  'rough',
  "olag, ~'s hubris",
  'olag',
  '~\'s retribution',
  'spellrune howler',
  "echo of death's wail",
  "~'s hammer",
  '~, pious apparition',
  '~, roaring flame',
  'awoken horror',
  'gorm',
  'explosion',
  'archive haunt',
  'stalking vampire',
  'b.f.m',
  '~, dinobot leader',
  '~, ferocious king',
)

# Top priority run before everything else before matching starts.
regexes: tuple[tuple[str, str], ...] = (
  ('partner with .*', 'partner with ~~'), # Specific references to other cards should get replaced with ~~.
  ('’', "'"), # replace special character single quote with normal single quote.
  (r'{a}', 'acorn counter'),
  (r'{e}', 'energy counter'),
  (r'{hr}', 'half red'),
  (r'{hw}', 'half white'),
  (r'{([^}]+)}', r' [[symbol]] \1 '), # move symbols to a separate start symbol.
  ('®', ''), # this symbol is not useful.
  (r'\([^\)]+\)', ''), # remove reminder text
)
