tokens = ('[[nil]]',
  "'",
  "'s",
  '!'
  '"',
  '##ed', # past tense verb suffix like in attacked
  '##er', # verb suffix to make a noun for actor like in attacker
  '##ing', # active tense verb suffix like in attacking
  '##s', # plural noun s suffix like in players
  '##vs', # verb s suffix like in attacks
  '##est', 
  '&',
  '*',
  '+',
  ',',
  '-',
  '.5',
  '/',
  '0',
  '1',
  '1,000',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '2',
  '20',
  '200',
  '25',
  '26',
  '3',
  '30',
  '4',
  '40',
  '5',
  '50',
  '6',
  '7',
  '8',
  '9',
  '99',
  ':',
  ';',
  '[',
  '[[card]]',
  '[[cost]]',
  '[[loyalty]]',
  '[[mask]]',
  '[[oracle]]',
  '[[power]]',
  '[[toughness]]',
  '[[type]]',
  '[[bureaucracy]]',
  '[[bureaucracycond]]',
  '\n',
  ']',
  'a',
  'abian',
  'ability',
  'able',
  'above',
  'absolutely-removed-from-the-freaking-game-forever',
  'absorb',
  'accept',
  'acorn',
  'action',
  'activate',
  'active',
  'adapt',
  'add',
  'addition',
  'additional',
  'adventure',
  'adventuring',
  'advise',
  'advisor',
  'advocate',
  'aegis',
  'aetherborn',
  'affect',
  'affinity',
  'afflict',
  'after',
  'afterlife',
  'aftermath',
  'again',
  'against',
  'age',
  'agenda',
  'agents of s.n.e.a.k.', #UN
  'aggressive',
  'aim',
  'air',
  'ajani',
  'alara',
  'alien',
  'alive',
  'all',
  'ally',
  'alone',
  'alphabet', #UN
  'alphabetically', #UN
  'already',
  'also',
  'amass',
  'american', #UN
  'aminatou',
  'among',
  'amount',
  'amplify',
  'and',
  'and/or',
  'angel',
  'angrath',
  'annhilator',
  'answer', # UN
  'ante',
  'antelope',
  'antiquities',
  'any',
  'anytime',
  'anywhere',
  'ape',
  'appears', # UN
  'apply',
  'arabian nights',
  'arachnus web',
  'arcane',
  'archer',
  'archon',
  'are',
  'area',
  'arkhos',
  'arlinn',
  'arm', # UN
  'army',
  'arrow',
  'arrowhead',
  'art',
  'artifact',
  'artificer',
  'artist',
  'as',
  'ascend',
  'ashiok',
  'ask', # UN
  'assassin',
  'assemble', # UN
  'assembly-worker',
  'assign',
  'assist',
  'at',
  'atog',
  'attach',
  'attack',
  'audibly flicks', # UN
  'augment', # UN
  'aura',
  'aurochs',
  'autobot', # UN
  'autumn', # autumn
  'avatar',
  'awaken',
  'awakening',
  'aware',
  'away',
  'azgol',
  'azra',
  'back',
  'badger',
  'bahamut',
  'balance',
  'ban',
  'band'
  'bank',
  'barbarian',
  'bard',
  'base',
  'basic',
  'basilisk',
  'basri',
  'bat',
  'battle cry',
  'battlefield',
  'bear',
  'beast',
  'beaver',
  'become',
  'beeble',
  'been',
  'before',
  'begin',
  'behemoth',
  'behind',
  'beholder',
  'being',
  'belenon',
  'bell',
  'below',
  'bend',
  'beneath',
  'berserker',
  'bestow',
  'between',
  'best',
  'beyond',
  'bid',
  'bird',
  'black',
  'bland',
  'blank',
  'blaze',
  'blinkmoth',
  'block',
  'blood',
  'bloodline',
  'bloodthirst',
  'blue',
  'blurry',
  'boar',
  'boast'
  'body',
  'bolas',
  'bolster'
  'book',
  'booster',
  'border',
  'both',
  'bottom',
  'bound',
  'bounty',
  'bow',
  'bracketed',
  'brainiac',
  'breath-holding',
  'bribery',
  'brick',
  'bringer',
  'brushwagg',
  'bureaucrat',
  'bushido',
  'buzz',
  'by',
  'cage',
  'calix',
  'camarid',
  'came',
  'camel',
  'can',
  'capital',
  'card',
  'caribou',
  'carrier',
  'carrion',
  'cartouche',
  'cascade',
  'cast',
  'cat',
  'catch',
  'cause',
  'ceases',
  'centaur',
  'cephalid',
  'chair',
  'challenge',
  'chameleon',
  'champion',
  'chandra',
  'change',
  'changeling',
  'chaos',
  'characteristics',
  'charge',
  'charisma check',
  'chicken',
  'child',
  'chimera',
  'chip',
  'choice',
  'choose',
  'chorus',
  'chosen',
  'chronicle',
  'cipher',
  'citizen',
  "city's blessing",
  'clamfolk',
  'clap',
  'clash',
  'class',
  'cleanup',
  'cleave',
  'cleric',
  'closest',
  'clothing',
  'cluck',
  'clue',
  'cockatrice',
  'coin',
  'collector number',
  'color',
  'combat',
  'combination',
  'combine',
  'come',
  'command',
  'commander',
  'common',
  'compleated',
  'complete',
  'completely',
  'compliment',
  'condemnation',
  'consumes and confuses'
  'consonant',
  'conspiracy',
  'conspire',
  'construct',
  'constructed format',
  'contains',
  'continues',
  'continuously',
  'contraption',
  'control',
  'convert',
  'convoke',
  'copy',
  'corpse',
  'correct',
  'correctly',
  'corruption',
  'cost',
  'could',
  'counter',
  'counts',
  'cover',
  'cow',
  'coward',
  'crab',
  'crank',
  'create',
  'creature',
  'credit',
  'crew',
  'croak',
  'crocodile',
  'crossbreed labs',
  'crow',
  'crystal',
  'cube',
  'cumulative',
  'currency',
  'current hour',
  'curse',
  'cyborg',
  'cycle',
  'cyclops',
  'dack',
  'dakkon',
  'damage',
  'daretti',
  'dark outdoors',
  'dash',
  'dauthi',
  'davriel',
  'day',
  'deal',
  'death',
  'deathtouch',
  'decayed',
  'decide',
  'declare',
  'deer',
  'defender',
  'defending',
  'delay',
  'delete the first letter',
  'delve',
  'demigod',
  'demon',
  'demonstrate',
  'denial',
  'denim',
  'depletion',
  'desert',
  'deserter',
  'designer',
  'despair',
  'destroy',
  'detain',
  'determine',
  'dethrone',
  'devil',
  'devoid',
  'devotion',
  'devour',
  'dice',
  'did',
  'die',
  'different',
  'differently',
  'dihada',
  'dinobot',
  'dinosaur',
  'direction',
  'directly',
  'discard',
  'distance',
  'distribute',
  'disturb',
  'divide',
  'divinity',
  'djinn',
  'do',
  'dog',
  'dominaria',
  'domri',
  'done',
  'donkey',
  'doodle',
  'doom',
  'double',
  'dovin',
  'down',
  'draft',
  'dragon',
  'drake',
  'draw',
  'dreadnought',
  'dream',
  'dredge',
  'drink',
  'drone',
  'drop',
  'druid',
  'dryad',
  'duck',
  'dungeon',
  'duplication',
  'during',
  'dwarf',
  'e',
  'each',
  'earth',
  'eating',
  'echo',
  'effect',
  'efreet',
  'egg',
  'either',
  'elbow',
  'elder',
  'eldrazi',
  'elemental',
  'elephant',
  'elf',
  'elixir',
  'elk',
  'ellywick',
  'else',
  'elspeth',
  'embalm',
  'ember',
  'emblem',
  'emerge',
  'empty',
  'enchant',
  'enchantment',
  'encore',
  'encounter',
  'end',
  'enemy',
  'english',
  'enlightened',
  'enter',
  'entwine',
  'eon',
  'epic',
  'equal',
  'equilor',
  'equip',
  'equipment',
  'ergamon',
  'errata',
  'escalate',
  'escape',
  'estrid',
  'eternalize',
  'etherium cell',
  'even',
  'evenly',
  'ever',
  'every',
  'everything',
  'evoke',
  'evolve',
  'exactly',
  'exalted',
  'except',
  'excess',
  'exchange'
  'exert',
  'exile',
  'exist',
  'expansion',
  'experience',
  'exploit',
  'explore',
  'extort',
  'extra',
  'eye',
  'eyeball',
  'eyestalk',
  'fabacin',
  'fabricate',
  'face',
  'fact',
  'fade',
  'faerie',
  'falls',
  'far',
  'fate',
  'fateseal',
  'fear',
  'feather',
  'feet',
  'ferret',
  'fetch',
  'few',
  'fight',
  'filibuster',
  'find',
  'finger',
  'fingernail',
  'finish', # also a card name special case written up for the card that uses it.
  'finishes',
  'first',
  'fish',
  'fizzles',
  'flagbearer',
  'flame',
  'flanking',
  'flash',
  'flashback',
  'flavor',
  'flavorful',
  'flip',
  'flood',
  'flying',
  'foe',
  'follow',
  'food',
  'foot',
  'for',
  'forehead',
  'foreshadow',
  'forest',
  'foretell',
  'fortify',
  'fortification',
  'found',
  'fox',
  'fractal',
  'free',
  'freyalise',
  'friend',
  'friends forever',
  'frog',
  'from',
  'frost',
  'full',
  'fun',
  'fungus',
  'funk',
  'fuse',
  'gain',
  'game',
  'gamer',
  'gargoyle',
  'garruk',
  'gate',
  'gem',
  'gender',
  'generic',
  'germ',
  'get',
  'ghostform',
  'giant',
  'gideon',
  'gift',
  'give',
  'glasspool mimic',
  'glyph',
  'gnoll',
  'gnome',
  'go',
  'goad',
  'goat',
  'goblin',
  'goblin explosioneers',
  'god',
  'gold',
  'golem',
  'gorgon',
  'gorilla',
  'grace',
  'graft',
  'grandchild',
  'graveborn',
  'grave',
  'graveyard',
  'great',
  'greed',
  'green',
  'gremlin',
  'griffin',
  'grist',
  'growl',
  'growth',
  'guess',
  'gus',
  'guy',
  'had',
  'hag',
  'half',
  'halfling',
  'hamster',
  'hand',
  'harvest',
  'has',
  'haste',
  'hatching',
  'hatchling',
  'hatificer',
  'hats'
  'haunt',
  'have',
  'he',
  'head',
  'head to askurza.com and click',
  'heads',
  'healing',
  'height',
  'held',
  'hellion',
  'her',
  'hexproof',
  'hidden',
  'hide',
  'hideaway',
  'high'
  'high-5',
  'him',
  'himself',
  'hippo',
  'hippogriff',
  'his',
  'historic',
  'hit', # also has a card of the same name.
  'hits',
  'hokey pokey',
  'homage',
  'homarid',
  'homelands',
  'homunculus',
  'hone',
  'hoofprint',
  'hornet',
  'horror',
  'horse',
  'horsemanship',
  'host',
  'hounds',
  'hour',
  'hourglass',
  'how',
  'huatli',
  'human',
  'hunger',
  'hydra',
  'hyena',
  'ice',
  'identity',
  'if',
  'ignore',
  'illegal',
  'illusion',
  'immediately',
  'imp',
  'improvise',
  'in',
  'in a deep, booming voice, “Presenting … ”',
  'incarnation',
  'inches',
  'include',
  'increase',
  'indestructible',
  'indicated',
  'infect',
  'infection',
  'ingest',
  'inkling',
  'innistrad',
  'insect',
  'install',
  'instance',
  'instant',
  'instead',
  'insult',
  'interplanar',
  'intervention',
  'intimidate',
  'into',
  'investigate',
  'invitation',
  'inzerva',
  'iquatana',
  'is',
  'island',
  'isolation',
  'it',
  'item',
  'itself',
  'jace',
  'jackal',
  'javelin',
  'jaya',
  'jellyfish',
  'jeska',
  'juggernaut',
  'jump-start',
  'just',
  'kaito',
  'kaldheim',
  'kamigawa',
  'kangaroo',
  'karn',
  'karsus',
  'kasmina',
  'kavu',
  'kaya',
  'kephalai',
  'key',
  'keyword',
  'khans',
  'ki',
  'kick',
  'kill',
  'killbot',
  'kind',
  'kinshala',
  'kiora',
  'kirin',
  'kithkin',
  'knight',
  'knocked',
  'knowledge',
  'kobold',
  'kolbahan',
  'koni and richard continue the game and play all games as partners forever.'
  'kor',
  'koth',
  'kraken',
  'kyneth',
  'label',
  'lady of proper etiquette',
  'lair',
  'lamia',
  'lammasu',
  'land',
  'landmark',
  'large',

  'league of dastardly doom',
  'mana',
  'mythic championship',
  'nerf blaster',
  'not',
  'player',
  'rebecca guay',
  'ring or imitate a bell',
  'sacrifice',
  "shuffle all cards in the game together and deal them into three deck. the game continues with a new player."
  'sided',
  "sneak into your parents' closet to get a deck. your new brother is joining the game."
  'squared',
  'stand up, flap your arms',
  'symbol',
  'have a staring contest',
  'text box',
  'that',
  'the biggest, baddest, nastiest,'
  'tomb of annihilation',
  'totem armor',
  'value',
  'vote',
  'walk',
  'wayne england',
  'when',
  'wrestle', # UN
  'x',
  'y',
  'z',
  '~',
  '~~',
  '—',
  "“Ach! Hans, Run! It's the …”",
  "“I'm Rubber, You're Glue. Everything bounces off me and sticks to you”",
)

## TODO
# Everything from atinlay igpay except name

# if the left matches replace with the right. Priority over token matching.
extra_productions = (
  (' ', ()),
  ('abilities', ('ability', '##s')),
  ('accepted', ('accept', '##ed')),
  ('acrificesay', ('sacrifice',)),
  ('actions', ('action', '##s')),
  ('activated', ('activate', '##ed')),
  ('activates', ('activate', '##vs')),
  ('activating', ('activate', '##ing')),
  ('adapts', ('adapt', '##vs')),
  ('added', ('add', '##ed')),
  ('adds', ('add', '##vs')),
  ('advisors', ('advisor', '##s')),
  ('allies', ('ally', '##s')),
  ('amassed', ('amass', '##ed')),
  ('an', ('a',)),
  ('angels', ('angel', '##s')),
  ('answer', ('answer', '##vs')),
  ('antes', ('ante', '##vs')),
  ('apes', ('ape', '##s')),
  ('arcane—', ('arcane',)),
  ("aren't", ('are', 'not',)),
  ('arm-wrestle', ('arm', 'wrestle')),
  ('arms', ('arm', '##s')),
  ('artifacts', ('artifact', '##s')),
  ('ascended', ('ascend', '##ed')),
  ('asking', ('ask', '##ing')),
  ('asks', ('ask', '##vs')),
  ('assembles', ('assemble', '##vs')),
  ('assigned', ('assign', '##ed')),
  ('assigns', ('assign', '##vs')),
  ('attached', ('attach', '##ed')),
  ('attaches', ('attach', '##ss')),
  ('attacked', ('attack', '##ed')),
  ('attacker', ('attack', '##er')),
  ('attacking', ('attack', '##ing')),
  ('attacks', ('attack', '##vs')),
  ('auras', ('aura', '##s')),
  ('balanced', ('balance', '##ed')),
  ('balances', ('balance', '##vs')),
  ('banded', ('band', '##ed')),
  ('banding', ('band', '##ing')),
  ('bands', ('band', '##s')),
  ('banned', ('ban', '##ed')),
  ('bats', ('bat', '##s')),
  ('beasts', ('beast', '##s')),
  ('became', ('become', '##ed')),
  ('becomes', ('become', '##s')),
  ('becoming', ('become', '##ing')),
  ('beebles', ('beeble', '##s')),
  ('begain', ('begin', '##ed')),
  ('beginning', ('begin', '##ing')),
  ('bidder', ('bid', '##er')),
  ('bidding', ('bid', '##ing')),
  ('birds', ('bird', '##s')),
  ('black-bordered', ('black', 'bordered')),
  ('blocked', ('block', '##ed')),
  ('blockers', ('block', '##er', '##s')),
  ('blocking', ('block', '##ing')),
  ('blocks', ('block', '##s')),
  ('borders', ('border', '##s')),
  ('brainiacs', ('brainiac', '##s')),
  ('buyback—', ('buyback',)),
  ('camarids', ('camarid', '##s')),
  ('cannot', ('can', 'not')),
  ('cards', ('card', '##s')),
  ('casting', ('cast', '##ing')),
  ('casts', ('cast', '##vs')),
  ('catches', ('catch', '##vs')),
  ('cats', ('cat', '##s')),
  ('causes', ('cause', '##vs')),
  ('cephalids', ('cephalid', '##s')),
  ('championed', ('champion', '##ed')),
  ('changed', ('change', '##ed')),
  ('changing', ('change', '##ing')),
  ('choices', ('choice', '##s')),
  ('chooses', ('choose', '##vs')),
  ('choosing', ('choose', '##ing')),
  ('chose', ('choose', '##ed')),
  ('one and one-half', ('1', '.5')),
  ('²', ('squared',)),
  ('clerics', ('cleric', '##s')),
  ('clues', ('clue', '##s')),
  ('coins', ('coin', '##s')),
  ('colored', ('color', '##ed')),
  ('colorless', ('not', 'color', '##ed')),
  ('colors', ('color', '##s')),
  ('combined', ('combine', '##ed')),
  ('comes', ('come', '##vs')),
  ('coming', ('come', '##ing')),
  ('commanders', ('commander', '##s')),
  ('completed', ('complete', '##ed')),
  ('pursuant to subsection 3.1(4) of richard’s rules of order, at the beginning of the upkeep of each participant in this game of the magic: the gathering trading card game, that player performs all actions in the sequence of previously added actions, in the order those actions were added, then adds another action to the end of the action queue. all actions must be simple physical or verbal actions that a player can perform while sitting in a chair, without jeopardizing the health and security of said player.', ('[[bureaucracy]]',)),
  ('any player', ('a', 'player')),
  ('does not perform all the prescribed actions in the correct order', ('[[bureaucracycond]]',)),
  ('said player', ('that', 'player',)),
  ('complement of cards in hand', ('hand',)),
  ('contraptions', ('contraption', '##s')),
  ('controlled', ('control', '##ed')),
  ('controller', ('control', '##er')),
  ('controls', ('control', '##vs')),
  ('converted mana cost', ('mana', 'value')),
  ('convoked', ('convoke', '##ed')),
  ('copied', ('copy', '##ed')),
  ('copies', ('copy', '##s')),
  ('copying', ('copy', '##ing')),
  ('costs', ('cost', '##s')),
  ("couldn't", ('could', 'not')),
  ('counters', ('counter', '##s')),
  ('countered', ('counter', '##ed')),
  ('covered', ('cover', '##ed')),
  ('covering', ('cover', '##ing')),
  ('cowards', ('coward', '##s')),
  ('crabs', ('crab', '##s')),
  ('creates', ('create', '##vs')),
  ('created', ('create', '##ed')),
  ('creatures', ('creature', '##s')),
  ('crews', ('crew', '##vs')),
  ('crewed', ('crew', '##ed')),
  ('curses', ('curse', '##s')),
  ('cycles', ('cycle', '##vs')),
  ('cycled', ('cycle', '##ed')),
  ('cycling', ('cycle', '##ing')),
  ('cycling—', ('cycle', '##ing')),
  ('d20', ('20', 'sided', 'dice')),
  ('d10', ('10', 'sided', 'dice')),
  ('d12', ('12', 'sided', 'dice')),
  ('d4', ('4', 'sided', 'dice')),
  ('d6', ('6', 'sided', 'dice')),
  ('d8', ('8', 'sided', 'dice')),
  ('deals', ('deal', '##vs')),
  ('dealt', ('deal', '##ed')),
  ('decides', ('decide', '##vs')),
  ('decks', ('deck', '##s')),
  ('declared', ('declare', '##ed')),
  ('declaring', ('declare', '##ing')),
  ('demons', ('demon', '##s')),
  ('deserts', ('desert', '##s')),
  ('destroyed', ('destroy', '##ed')),
  ('destroys', ('destroy', '##vs')),
  ('determined', ('determine', '##ed')),
  ('devils', ('devil', '##s')),
  ('devoured', ('devour', '##ed')),
  ("didn't", ('did', 'not')),
  ('died', ('die', '##ed')),
  ('dies', ('die', '##vs')),
  ('dinosaurs', ('dinosaur', '##s')),
  ('discarded', ('discard', '##ed')),
  ('discarding', ('discard', '##ing')),
  ('discards', ('discard', '##vs')),
  ('distributes', ('distribute', '##vs')),
  ('divides', ('divide', '##vs')),
  ('divided', ('divide', '##ed')),
  ('djinns', ('djinn', '##s')),
  ('does', ('do', '##vs')),
  ("doesn't", ('do', '##vs', 'not')),
  ('dogs', ('dog', '##s')),
  ('doing', ('do', '##ing')),
  ("don't", ('do', 'not')),
  ('doubles', ('double', '##vs')),
  ('drafted', ('draft', '##ed')),
  ('drafting', ('draft', '##ing')),
  ('drafts', ('draft', '##vs')),
  ('dragons', ('dragon', '##s')),
  ('drawing', ('draw', '##ing')),
  ('drawn', ('draw', '##er')),
  ('draws', ('draw', '##vs')),
  ('drew', ('draw', '##ed')),
  ('dropped', ('drop', '##ed')),
  ('druids', ('druid', '##s')),
  ('dungeons', ('dungeon', '##s')),
  ('dwarves', ('dwarf', '##s')),
  ('dying', ('die', '##ing')),
  ('eaturecraw', ('creature',)),
  ('echo—', ('echo',)),
  ('effects', ('effect', '##s')),
  ('efreets', ('efreet', '##s')),
  ('elementals', ('elemental', '##s')),
  ('elves', ('elf', '##s')),
  ('embalmed', ('embalm', '##ed')),
  ('emblems', ('emblem', '##s')),
  ('enchanted', ('enchant', '##ed')),
  ('enchanting', ('enchant', '##ing')),
  ('enchantments', ('enchantment', '##s')),
  ('ended', ('end', '##ed')),
  ('ending', ('end', '##ing')),
  ('ends', ('end', '##vs')),
  ('enemy-colored', ('enemy', 'color', '##ed')),
  ('entered', ('enter', '##ed')),
  ('entering', ('enter', '##ing')),
  ('enters', ('enter', '##vs')),
  ('entwine—', ('entwine',)),
  ('enwhay', ('when',)),
  ('equipped', ('equip', '##ed')),
  ('equip—', ('equip',)),
  ('escalate—', ('escalate',)),
  ('escapes', ('escape', '##vs')),
  ('escaped', ('escape', '##ed')),
  ('eternalize—', ('eternalize',)),
  ('evoke—', ('evoke',)),
  ('evolves', ('evolve', '##vs')),
  ('exchanged', ('exchange', '##ed')),
  ('exerted', ('exert', '##ed')),
  ('exiled', ('exile', '##ed')),
  ('exiles', ('exile', '##vs')),
  ('exiling', ('exile', '##ing')),
  ('expansion-symbol', ('expansion', 'symbol')),
  ('exploits', ('exploit', '##vs')),
  ('exploited', ('exploit', '##ed')),
  ('explores', ('explore', '##vs')),
  ('eyes', ('eye', '##s')),
  ('face-down', ('face', 'down')),
  ('face-up', ('face', 'up')),
  ('facing', ('face', '##ing')),
  ('fading', ('fade', '##ing')),
  ('faeries', ('faerie', '##s')),
  ('fewer', ('few', '##er')),
  ('fewest', ('few', '##est')),
  ('fights', ('fight', '##vs')),
  ('fingers', ('finger', '##s')),
  ('finish voting', ('finish', 'vote', '##ing')),
  ('firstest', ('first', '##est')),
  ('flashback—', ('flashback',)),
  ('flipped', ('flip', '##ed')),
  ('flipping', ('flip', '##ing')),
  ('flips', ('flip', '##s')),
  ('followed', ('follow', '##ed')),
  ('following', ('follow', '##ing')),
  ('foods', ('food', '##s')),
  ('forests', ('forest', '##s')),
  ('foretelling', ('foretell', '##ing')),
  ('foretold', ('foretell', '##ed')),
  ('fortified', ('fortify', '##ed')),
  ('fourth', ('4',)),
  ('gained', ('gain', '##ed')),
  ('gains', ('gain', '##vs')),
  ('games', ('game', '##s')),
  ('gates', ('gate', '##s')),
  ('gets', ('get', '##vs')),
  ('giants', ('giant', '##s')),
  ('goaded', ('goad', '##ed')),
  ('goats', ('goat', '##s')),
  ('goblins', ('goblin', '##s')),
  ('golems', ('golem', '##s')),
  ('gorgons', ('gorgon', '##s')),
  ('graveyards', ('graveyard', '##s')),
  ('greater', ('great', '##er')),
  ('greatest', ('great', '##est')),
  ('w', ('white',)),
  ('u', ('blue',)),
  ('b', ('black',)),
  ('r', ('red',)),
  ('g', ('green',)),
  ('c', ('colorless')),
  ('s', ('snow',)),
  ('gremlins', ('gremlin', '##s')),
  ('guesses', ('guess', '##vs')),
  ('guessed', ('guess', '##ed')),
  ("hadn't", ('had', 'not')),
  ('hands', ('hand', '##s')),
  ("hasn't", ('has', 'not')),
  ('haunted', ('haunt', '##ed')),
  ('haunting', ('haunt', '##ing')),
  ('haunts', ('haunt', '##vs')),
  ("haven't", ('have', 'not')),
  ('having', ('have', '##ing')),
  ('hides', ('hide', '##vs')),
  ('high-fives', ('high-5', '##s')),
  ('higher', ('high', '##er')),
  ('highest', ('high', '##est')),
  ('hit counter', ('hit', 'counter')),
  ('homarids', ('homarid', '##s')),
  ('horses', ('horse', '##s')),
  ('humans', ('human', '##s')),
  ('ikestray', ('strike',)),
  ('illusions', ('illusion', '##s')),
  ('including', ('include', '##ing')),
  ('increased', ('increase', '##ed')),
  ('inklings', ('inkling', '##s')),
  ('insects', ('insect', '##s')),
  ('instances', ('instance', '##s')),
  ('instants', ('instant', '##s')),
  ('investigated', ('investigate', '##ed')),
  ('investigates', ('investigate', '##vs')),
  ('islands', ('island', '##s')),
  ("isn't", ('is', 'not')),
  ('items', ('item', '##s')),
  ('its', ('it', "'s")),
  ("it's", ('it', 'is')),
  ('kicker', ('kick', '##er')),
  ('kicked', ('kick', '##ed')),
  ('kicker—', ('kick', '##er')),
  ('kicks', ('kick', '##vs')),
  ('kinds', ('kind', '##s')),
  ('knights', ('knight', '##s')),
  ('did you know this creature has flying?', ('flying',)),
  ('kobolds', ('kobold', '##s')),
  ('krakens', ('kraken', '##s')),
  ('lands', ('land', '##s')),
)

# Replace with ~~. Priority over extra_productions
referenced_card_names = (
  'alpine watchdog',
  'empyrial archangel',
  "nissa, nature's artisan",
  'ashaya, the awoken world',
  'hammer of nazahn',
  'karox bladewing',
  'ignorant bliss',
  'crack the earth',
  'blazing volley',
  'seething song',
  'dance with devils',
  'flamebreak',
  'hellion eruption',
  'insurrection',
  'warp world',
  'bogbrew witch',
  'kobolds of kher keep',
  'chandra, bold pyromancer',
  'lightning bolt',
  'land mine',
  'boo',
  'the underworld cookbook',
  'disenchant',
  'braingeyser',
  'terror',
  'shivan dragon',
  'regrowth',
  'black lotus',
  'brambleweft behemoth',
  'nissa, genesis mage',
  'breathstealer',
  'feral shadow',
  "bride's gown",
  'bruna, the fading light',
  'brisela, voice of nightmares',
  'festering newt',
  'bubbling cauldron',
  'ral, caller of storms',
  'carnivore',
  "chandra, flame's catalyst",
  'mu yanling, celestial wind',
  'chittering host',
  'cloud sprite',
  "koma's coil",
  'crown of empires',
  'throne of empires',
  'nicol bolas, the deceiver',
  'peer through depths',
  'sift through sands',
  'the unspeakable',
  'basri, devoted paladin',
  'heart-piercer bow',
  'vial of dragonfire',
  'mulldrifter',
  'scepter of empires',
  'throne of empires',
  'crown of empires',
  'rowan, fearless sparkmage',
  'ashiok, sculptor of fears',
  'guan yu, sainted warrior',
  'zhang fei, fierce warrior',
  'rahilda, feral outlaw',
  "groom's finery",
  'hanweir garrison',
  "god pharaoh's gift",
  'godsire',
  'goldmeadow harrier',
  'guenhwyvar',
  'gunk',
  'halvar, god of battle',
  'sword of kaldra',
  'shield of kaldra',
  'helm of kaldra',
  'garruk, savage herald',
  'elspeth, undaunted hero',
  'sunlit hoplite',
  'wolves of the hunt',
  'icy manalith',
  'igneous cur',
  'jace, ingenious mind-mage',
  'ajani, aspiring leader',
  'jiang yanggu',
  'keimi',
  'kelp',
  'keeper of kookus',
  'labyrinth of skophos',
  'marit lage',
)

# Replace with ~. Priority over referenced_card_names
extra_card_names = (
  'howling chorus',
  'silundi isle',
  'journey to the oracle',
  'lambholt butcher',
  "lanterns' lift",
  "tergrid's lantern",
  'lambholt ravager',
  'kazandu valley',
  "kazuul's cliffs",
  'khalni territory',
  'jwari ruins',
  'terror of kruin pass',
  'kaiso, memory of loyalty',
  'injury',
  'kabira plateau',
  'kirin-touched orochi',
  'jaraku the interloper',
  "sinner's judgement",
  'malicious invader',
  'ironfang',
  'lunarch inquisitors',
  'insidious mist',
  'moonrise intruder',
  'twinblade invocation',
  'ichiga who topples oaks',
  'hit',
  'incited rabble',
  'wildsong howler',
  'krallenhorde wantons',
  'infested werewolf',
  'krallenhorde killer',
  'hivis',
  'hinterland scourge',
  'timber shredder',
  'heaven',
  'hellkite overlord',
  'shatterskull, the hammer pass'
  'hazezon',
  'hazoret',
  'havengul mystery',
  "toralf's hammer",
  'hakka, whispering raven',
  'haktos',
  'perfected form',
  'gutter shortcut',
  'goka the unjust',
  'sejiri glacier',
  'graveyard glutton',
  'generous soul',
  'ghastly mimicry',
  'gatstaf ravagers',
  'gatstaf howler',
  'unimpeded trespasser',
  "arlinn, the moon's fury",
  'furious',
  'frenzied trapbreaker',
  'fragment of konda',
  'flamethrower sonata',
  'flameheart werewolf',
  'chandra, roaring flame',
  'inherited fiend',
  'finish',
  'grimlock, ferocious king',
  'poppet factory',
  'umara skyfalls',
  'ravager of the fells',
  'fangblade eviscerator',
  'howlpack of estwald',
  'fiborous entangler',
  'emeria, shattered skyclave',
  'embodiment of flame',
  'heaven',
  "olag, ludevic's hubris",
  'earth',
  'dronepack kindred',
  'drizzt',
  'hook-haunt drifter',
  'waildrifter',
  'abolisher of bloodlines',
  'agadeem, the undercrypt',
  'akoum teeth',
  'vessel of the all-consuming',
  'vildin-pack alpha',
  'howlpack alpha',
  'ulrich, uncontested alpha',
  'dire-strain anarchist',
  'arlinn, embraced by the moon',
  "ancestor's embrace",
  'werewolf of ancient hunger',
  'angelic enforcer',
  "animus of night's reach",
  'dennick, pious apparition',
  'morning apparition',
  'archdemon of greed',
  'avacyn, the purifier',
  'architect of restoration',
  'nicol bolas the arisen',
  'drogskol armaments',
  'assault',
  'azamuki, treachery incarnate',
  'baneclaw marauder',
  'bane of hanweir',
  'bala ged sanctuary',
  'ballista wielder',
  'b.o.b',
  'ashmouth dragon',
  'aurora of emrakul',
  'howlpack avenger',
  'axelrod',
  'skyclave basilica',
  'spitfire bastion',
  'gideon, battle-forged',
  'bearer of overwhelming truths',
  'bedazzle',
  'benevolent geist',
  'beyeen coast',
  'spectral binding',
  'biolume serpent',
  'blackbloom bog',
  'fangblade eviscerator',
  'twinblade invocation',
  'zof blodbog',
  'bloodsworn knight',
  'branch of boseiju',
  'branded howler',
  'krallenhorde howler',
  'neck breaker',
  'nightfall predator',
  'frenzied trapbreaker',
  'wrathful jailbreaker',
  'brinebound gift',
  'hagra broodpit',
  'homicidal brute',
  'burn',
  'restorative burst',
  'cackling culprit',
  'westvale cult leader',
  'carnage',
  'carnival',
  'ghostly castigator',
  'unhallowed cathar',
  'catlike curiosity',
  'catti-brie',
  'cardname',
  'pelakka caverns',
  'spikefield cave',
  'chapel shieldgeist',
  'chilling chronicle',
  'cipherbound spirit',
  'clever distraction',
  "edgar markov's coffin",
  'collision',
  'conduit of emrakul',
  'tibalt, cosmic impostor',
  'covetous geist',
  'wedding crasher',
  'creeping inn',
  'the ringhart crest',
  'crovax',
  'westvale cult leader',
  'cut',
  'deadly dancer',
  'darigaaz',
  'scion of darkness',
  'dauntless avenger',
  "katilda's rising dawn",
  'dead',
  'embrose, dean of shadow',
  'nassari, dean of expression',
  'deathbonnet hulk',
  'krothuss, lord of the deep',
  'demon-possessed witch',
  'departed soulkeeeper',
  'werewolf ransacker',
  'wayward disciple',
  "dragon-kami's egg",
  'erupting dreadwolf',
)

# Top priority run before everything else before matching starts.
regexes = (
  ('partner with .*', 'partner with ~~'), # Specific references to other cards should get replaced with ~~.
  ('’', "'"), # replace special character single quote with normal single quote.
  (r'{([^}]+)}', r' [[symbol]] \1 '), # move symbols to a separate start symbol.
  ('®', ''), # this symbol is not useful.
  (r'\([^)]+\)', ''), # remove reminder text
  (r"[^•]+ — ", ''), # remove ability words we want to focus on mechanics.
)
