tokens = ('[[nil]]',
  "'",
  "'s",
  '!'
  '"',
  '##ed',
  '##er',
  '##ing',
  '##s',
  '##vs',
  '&',
  '*',
  '+',
  ',',
  '-',
  '.5',
  '/',
  '0',
  '1',
  '1,000',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '2',
  '20',
  '200',
  '25',
  '26',
  '3',
  '30',
  '4',
  '40',
  '5',
  '50',
  '6',
  '7',
  '8',
  '9',
  '99',
  ':',
  ';',
  '[',
  '[[card]]',
  '[[cost]]',
  '[[loyalty]]',
  '[[mask]]',
  '[[oracle]]',
  '[[power]]',
  '[[toughness]]',
  '[[type]]',
  '\n',
  ']',
  'a',
  'abian',
  'ability',
  'able',
  'above',
  'absolutely-removed-from-the-freaking-game-forever',
  'absorb',
  'accept',
  'acorn',
  'action',
  'activate',
  'active',
  'adapt',
  'add',
  'addition',
  'additional',
  'adventure',
  'adventuring',
  'advise',
  'advisor',
  'advocate',
  'aegis',
  'aetherborn',
  'affect',
  'affinity',
  'afflict',
  'after',
  'afterlife',
  'aftermath',
  'again',
  'against',
  'age',
  'agenda',
  'agents of s.n.e.a.k.', #UN
  'aggressive',
  'aim',
  'air',
  'ajani',
  'alara',
  'alien',
  'alive',
  'all',
  'ally',
  'alone',
  'alphabet', #UN
  'alphabetically', #UN
  'already',
  'also',
  'amass',
  'american', #UN
  'aminatou',
  'among',
  'amount',
  'amplify',
  'and',
  'and/or',
  'angel',
  'angrath',
  'annhilator',
  'answer', # UN
  'ante',
  'antelope',
  'antiquities',
  'any',
  'anytime',
  'anywhere',
  'ape',
  'appears', # UN
  'apply',
  'arabian nights',
  'arachnus web',
  'arcane',
  'archer',
  'archon',
  'are',
  'area',
  'arkhos',
  'arlinn',
  'arm', # UN
  'army',
  'arrow',
  'arrowhead',
  'art',
  'artifact',
  'artificer',
  'artist',
  'as',
  'ascend',
  'ashiok',
  'ask', # UN
  'askurza.com',
  'assassin',
  'assemble', # UN
  'assembly-worker',
  'assign',
  'assist',
  'at',
  'atog',
  'attach',
  'attack',
  'audibly', # UN
  'augment', # UN
  'aura',
  'aurochs',
  'autobot', # UN
  'autumn', # autumn
  'avatar',
  'awaken',
  'awakening',
  'aware',
  'away',
  'azgol',
  'azra',
  'back',
  'badger',
  'bahamut',
  'balance',
  'ban',
  'band'
  'bank',
  'barbarian',
  'bard',
  'base',
  'basic',
  'basilisk',
  'basri',
  'bat',
  'battle cry',
  'battlefield',
  'bear',
  'beast',
  'beaver',
  'become',
  'beeble',
  'been',
  'before',
  'begin',
  'behemoth',
  'behind',
  'beholder',
  'being',
  'belenon',
  'bell',
  'below',
  'bend',
  'beneath',
  'berserker',
  'bestow',
  'between',
  'best',
  'beyond',
  'bid',
  'bird',
  'black',
  'bland',
  'blank',
  'blaze',
  'blinkmoth',
  'block',
  'blood',
  'bloodline',
  'bloodthirst',
  'blue',
  'blurry',
  'boar',
  'boast'
  'body',
  'bolas',
  'bolster'
  'book',
  'booster',
  'border',
  'both',
  'bottom',
  'bounty',
  'bow',
  'bracketed',
  'brainiac',
  'breath-holding',
  'bribery',
  'brick',
  'bringer',
  'brother',
  'brushwagg',
  'bureaucrat',
  'bushido',
  'buzz',
  'by',
  'cage',
  'calix',
  'camarid',
  'came',
  'camel',
  'can',
  'capital',
  'card',
  'caribou',
  'carrier',
  'carrion',
  'cartouche',
  'cascade',
  'cast',
  'cat',
  'catch',
  'cause',
  'ceases',
  'centaur',
  'cephalid',
  'chair',
  'challenge',
  'chameleon',
  'champion',
  'chandra',
  'change',
  'changeling',
  'chaos',
  'characteristics',
  'charge',
  'charisma check',
  'chicken',
  'child',
  'chimera',
  'chip',
  'choice',
  'choose',
  'chorus',
  'chosen',
  'chronicle',
  'cipher',
  'citizen',
  "city's blessing",
  'clamfolk',
  'clap',
  'clash',
  'class',
  'cleanup',
  'd',
  'etherium cell',
  'in a deep, booming voice, “Presenting … ”',
  'mythic championship',
  'nerf blaster',
  'not',
  'sacrifice',
  'squared',
  'tomb of annihilation',
  'totem armor',
  'wrestle', # UN
  'text box',
  'the biggest, baddest, nastiest,'
  'x',
  'y',
  'z',
  '~',
  '~~',
  '—',
  "“Ach! Hans, Run! It's the …”",
  "“I'm Rubber, You're Glue. Everything bounces off me and sticks to you”",
)

## TODO
# attaches
# attached
# assigns
# assigned
# assembles
# asks
# asking
# Everything from atinlay igpay except name

# if the left matches replace with the right. Priority over token matching.
extra_productions = (
  (' ', ()),
  ('abilities', ('ability', '##s')),
  ('accepted', ('accept', '##ed')),
  ('acrificesay', ('sacrifice',)),
  ('actions', ('action', '##s')),
  ('activated', ('activate', '##ed')),
  ('activates', ('activate', '##vs')),
  ('activating', ('activate', '##ing')),
  ('adapts', ('adapt', '##vs')),
  ('added', ('add', '##ed')),
  ('adds', ('add', '##vs')),
  ('advisors', ('advisor', '##s')),
  ('allies', ('ally', '##s')),
  ('amassed', ('amass', '##ed')),
  ('an', ('a',)),
  ('angels', ('angel', '##s')),
  ('answer', ('answer', '##vs')),
  ('antes', ('ante', '##vs')),
  ('apes', ('ape', '##s')),
  ('arcane—', ('arcane',)),
  ("aren't", ('are', 'not',)),
  ('arm-wrestle', ('arm', 'wrestle')),
  ('arms', ('arm', '##s')),
  ('artifacts', ('artifact', '##s')),
  ('ascended', ('ascend', '##ed')),
  ('asking', ('ask', '##ing')),
  ('asks', ('ask', '##vs')),
  ('assembles', ('assemble', '##vs')),
  ('assigned', ('assign', '##ed')),
  ('assigns', ('assign', '##vs')),
  ('attached', ('attach', '##ed')),
  ('attaches', ('attach', '##ss')),
  ('attacked', ('attack', '##ed')),
  ('attacker', ('attack', '##er')),
  ('attacking', ('attack', '##ing')),
  ('attacks', ('attack', '##vs')),
  ('auras', ('aura', '##s')),
  ('balanced', ('balance', '##ed')),
  ('balances', ('balance', '##vs')),
  ('banded', ('band', '##ed')),
  ('banding', ('band', '##ing')),
  ('bands', ('band', '##s')),
  ('banned', ('ban', '##ed')),
  ('bats', ('bat', '##s')),
  ('beasts', ('beast', '##s')),
  ('became', ('become', '##ed')),
  ('becomes', ('become', '##s')),
  ('becoming', ('become', '##ing')),
  ('beebles', ('beeble', '##s')),
  ('begain', ('begin', '##ed')),
  ('beginning', ('begin', '##ing')),
  ('bidder', ('bid', '##er')),
  ('bidding', ('bid', '##ing')),
  ('birds', ('bird', '##s')),
  ('black-bordered', ('black', 'bordered')),
  ('blocked', ('block', '##ed')),
  ('blockers', ('block', '##er', '##s')),
  ('blocking', ('block', '##ing')),
  ('blocks', ('block', '##s')),
  ('borders', ('border', '##s')),
  ('brainiacs', ('brainiac', '##s')),
  ('buyback—', ('buyback',)),
  ('camarids', ('camarid', '##s')),
  ('cannot', ('can', 'not')),
  ('cards', ('card', '##s')),
  ('casting', ('cast', '##ing')),
  ('casts', ('cast', '##vs')),
  ('catches', ('catch', '##vs')),
  ('cats', ('cat', '##s')),
  ('causes', ('cause', '##vs')),
  ('cephalids', ('cephalid', '##s')),
  ('championed', ('champion', '##ed')),
  ('changed', ('change', '##ed')),
  ('changing', ('change', '##ing')),
  ('choices', ('choice', '##s')),
  ('chooses', ('choose', '##vs')),
  ('choosing', ('choose', '##ing')),
  ('chose', ('choose', '##ed')),
  ('one and one-half', ('1', '.5')),
  ('²', ('squared',)),
)

# Replace with ~~. Priority over extra_productions
referenced_card_names = (
  'alpine watchdog',
  'empyrial archangel',
  "nissa, nature's artisan",
  'ashaya, the awoken world',
  'hammer of nazahn',
  'karox bladewing',
  'ignorant bliss',
  'crack the earth',
  'blazing volley',
  'seething song',
  'dance with devils',
  'flamebreak',
  'hellion eruption',
  'insurrection',
  'warp world',
  'bogbrew witch',
  'kobolds of kher keep',
  'chandra, bold pyromancer',
  'lightning bolt',
  'land mine',
  'boo',
  'the underworld cookbook',
  'disenchant',
  'braingeyser',
  'terror',
  'shivan dragon',
  'regrowth',
  'black lotus',
  'brambleweft behemoth',
  'nissa, genesis mage',
  'breathstealer',
  'feral shadow',
  "bride's gown",
  'bruna, the fading light',
  'brisela, voice of nightmares',
  'festering newt',
  'bubbling cauldron',
  'ral, caller of storms',
  'carnivore',
  "chandra, flame's catalyst",
  'mu yanling, celestial wind',
  'chittering host',
  'howling chorus',
)

# Replace with ~. Priority over referenced_card_names
extra_card_names = (
  'abolisher of bloodlines',
  'agadeem, the undercrypt',
  'akoum teeth',
  'vessel of the all-consuming',
  'vildin-pack alpha',
  'howlpack alpha',
  'ulrich, uncontested alpha',
  'dire-strain anarchist',
  "ancestor's embrace",
  'werewolf of ancient hunger',
  'angelic enforcer',
  "animus of night's reach",
  'dennick, pious apparition',
  'morning apparition',
  'archdemon of greed',
  'avacyn, the purifier',
  'architect of restoration',
  'nicol bolas the arisen',
  'drogskol armaments',
  'assault',
  'azamuki, treachery incarnate',
  'baneclaw marauder',
  'bane of hanweir',
  'bala ged sanctuary',
  'ballista wielder',
  'b.o.b',
  'ashmouth dragon',
  'aurora of emrakul',
  'howlpack avenger',
  'axelrod',
  'skyclave basilica',
  'spitfire bastion',
  'gideon, battle-forged',
  'bearer of overwhelming truths',
  'bedazzle',
  'benevolent geist',
  'beyeen coast',
  'spectral binding',
  'biolume serpent',
  'blackbloom bog',
  'fangblade eviscerator',
  'twinblade invocation',
  'zof blodbog',
  'bloodsworn knight',
  'branch of boseiju',
  'branded howler',
  'neck breaker',
  'nightfall predator',
  'frenzied trapbreaker',
  'wrathful jailbreaker',
  'brinebound gift',
  'hagra broodpit',
  'homicidal brute',
  'burn',
  'restorative burst',
  'cackling culprit',
  'westvale cult leader',
  'carnage',
  'carnival',
  'ghostly castigator',
  'unhallowed cathar',
  'catlike curiosity',
  'catti-brie',
  'cardname',
  'pelakka caverns',
  'spikefield cave',
  'chapel shieldgeist',
  'chilling chronicle',
  'cipherbound spirit'
)

# Top priority run before everything else before matching starts.
regexes = (
  ('partner with .*', 'partner with ~~'),
  ('’', "'"),
  (r'{([^}]+)}', r'[[symbol]] \1'),
)
