version: '3'
services:
  mtgml:
    build:
      dockerfile: .docker/Dockerfile.eval
      context: ../
      # cache_from:
      #   - ${REPOSITORY}/mtgml:latest
    image: ${REPOSITORY}/mtgml:${TAG}
    environment:
      MTGML_AUTH_TOKENS: "testing"
      MTGML_AUTH_ENABLED: "False"
      MTGML_VERSION: "cubeartisan-testing"
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: 2000m
          memory: 8g
