version: '3'
services:
  mtgml:
    build:
      dockerfile: .docker/Dockerfile.eval
      context: ../
      # cache_from:
      #   - ${REPOSITORY}/mtgml:latest
    image: ${REPOSITORY}/mtgml:${TAG}
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: 32
          memory: 12g
